### ISSUE TITLE
Add FixedEffectModels.jl to benchmark

### ISSUE THREAD

**Issue by grantmcdermott** [lrberge/fixest#1]
I just came across this package yesterday. Really impressed with both the range of models covered and the implementation speed.

On the subject of speed, I was wondering if you could add some benchmark comparisons for the [FixedEffectModels.jl](https://github.com/matthieugomez/FixedEffectModels.jl) package in Julia. To the best of my knowledge, this is currently the cutting edge for HDFE implementations... at least as far as linear models go. My own quick benchmarks suggest that `fixest::feols` compares very favourably for medium sized data sets.

In case you're not familiar with Julia code, here's a quick and dirty example for running _one_ iteration of the largest model in your [benchmark simulation](https://drive.google.com/drive/folders/1-1M_vLGduByk5P3qHl7AMBBl85RzHpv7?usp=sharing). I'll cc the package owner @matthieugomez, who probably has better ideas for benchmarking and may also want to add **fixest** to his own benchmark comparisons.

```julia
### PRELIMINARIES ###
## Download files here: https://drive.google.com/drive/folders/1-1M_vLGduByk5P3qHl7AMBBl85RzHpv7?usp=sharing
## Then run `Data generation.R`
### END PRELIMINARIES ###

cd("/path/to/downloaded/files")

using RData

base_all = load("DATA/base_all_simulations_rect.RData", convert=true)
base_all = base_all["base_all"]

using FixedEffectModels

## Limit to the very last replication data frame (1,000,000 x 5)
base = base_all[40]

## Single thread
@time reg(base, @formula(log(y+1)~X1 + fe(dum_1) + fe(dum_2) + fe(dum_3)))

## Multi-threaded
@time reg(base, @formula(log(y+1)~X1 + fe(dum_1) + fe(dum_2) + fe(dum_3)), method = :lsmr_threads)

## GPU (requires working CUDA installation)
base.X1 = convert(Vector{Float32}, base[!, :X1]) ## Optional for performance boost
@time reg(base, @formula(log(y+1)~X1 + fe(dum_1) + fe(dum_2) + fe(dum_3)), method = :lsmr_gpu)
```

**Comment by matthieugomez** [comment]
Btw for GPU you don’t need to actually convert the vector to Float32. Just use double_precision = true as an option.

**Comment by lrberge** [comment]
Hi @grantmcdermott , this benchmark is supposed to compare the fastest available methods, so I'll definitely include @matthieugomez's method.

I don't know Julia at all, so I can't thank you enough for the very neat replication code you offered!
I'll try to update the benchmark in the coming week.

**Comment by lrberge** [comment]
Here it is, I updated the benchmark with @matthieugomez's method. I also increased the maximum number of observations for the OLS case to 10M. 

Our two methods are on a par in terms of speed: as we say in French, it's "bonnet blanc et blanc bonnet". On the benchmark, discounting the 10k obs., my method is faster but marginally so, and the differences do not scale with size. I guess it makes sense since we both use low level languages and we're close to the minimum number of floating point operations to perform such task.

Speed differences could appear for complex cases with low convergence rates among the fixed-effects. As opposed to the current benchmark, there the algorithm employed to accelerate the convergence would really matter, and I guess we employ different ones. I may add another benchmark in the future relating to this. 

Thanks for the pointer (and the kind words!) @grantmcdermott and kudos for your work @matthieugomez !

**Comment by grantmcdermott** [comment]
Super, thanks @lrberge. That matches my experience too. 

Before closing this issue I'll just reiterate that both packages are seriously impressive. I've found myself switching between them for different analyses lately. As you say, though, the different underlying algorithms &mdash; alternating projections vs concentrated max. likelihood &mdash; make for an interesting comparison. I still need to read [your paper](https://wwwen.uni.lu/content/download/110162/1299525/file/2018_13) to understand the latter properly, but it seems very powerful... not only in the way that it provides support for other model classes, but also (if I understand correctly) automatic clustering support. Perhaps impetus for a Julia implementation somewhere down the road @matthieugomez ;)

Hat tip to both of you!

**Comment by grantmcdermott** [comment]
PS &mdash; I've add a section on both packages to the new Library of Statistical Techniques (LOST) website. Feel free to edit if you spot any mistakes. https://lost-stats.github.io/Model_Estimation/fixed_effects_in_linear_regression.html
