### ISSUE TITLE
Request: test for fixest summary objects

### ISSUE THREAD

**Issue by karldw** [lrberge/fixest#111]
Hi @lrberge! 

I noticed that broom's `tidy.fixest` wasn't passing along the `se=` argument to `summary.fixest`. I wrote about the issue in https://github.com/tidymodels/broom/issues/1001.

As I mentioned in that issue, this is happening because the hacky test I wrote in [`is_fixest_summary`](https://github.com/tidymodels/broom/blob/1d6897515ecac6f072afe9c67138477e57d8eab9/R/fixest-tidiers.R#L74-L81) returns TRUE for some non-summary cases, because it's just looking for a `cov.scaled` name.  On non-summarized fixest objects, broom calls `summary`, but on ones it thinks have already been summarized, it doesn't, because the user may have already provided their preferred standard error, dof, etc. Calling `summary` again would overwrite those settings. 

Is there a convenient way to test whether a fixest object is already a summary?

``` r
library(broom)

res = fixest::feols(Sepal.Length ~ Sepal.Width + Petal.Length , cluster=~Species, data=iris)
# Wrong result here:
broom:::is_fixest_summary(res)
#> [1] TRUE
broom:::is_fixest_summary(summary(res))
#> [1] TRUE

identical(tidy(res), tidy(res, se="standard"))
#> [1] TRUE

res2 = fixest::feols(Sepal.Length ~ Sepal.Width + Petal.Length, data=iris)
# Right result here:
broom:::is_fixest_summary(res2)
#> [1] FALSE
```

Versions:
fixest 0.8.3, broom 0.7.5

Footnote: We definitely want to call summary, rather than just extracting `coeftable`, in the case with not-yet-summarized results, since this is the way to have other functions that depend on broom pass arguments to `summary.fixest`.

**Comment by lrberge** [comment]
Hi @karldw! (btw sorry for not replying yet to your other issue!)

No that's not a hacky way :-D It was the only way at the time when you implemented the method. Further, at the time we should not have called summary on a summary object because it would have triggered a re-computation of the VCOV with the default parameters instead of leaving it untouched. => So that was the right implementation!

Now things have changed a bit. I've added more flags to the results, in particular now there is a `summary` flag equal to `TRUE` or `NULL`. 

```R
library(fixest)
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

m = feols(y ~ x1, base)
m$summary
#> NULL
mm = summary(m)
mm$summary
#> [1] TRUE
```

Further, there's a new behavior: when summary is requested on a summary object, the VCOV is either untouched if no extra arguments are provided, either modified only for the new arguments (in particular `dof`).

```R
m_hetero = summary(m, se = "hetero")
m_hetero_sum = summary(m_hetero)
m_hetero_dof = summary(m_hetero, dof = dof(adj = FALSE))
etable(m_hetero, m_hetero_sum, m_hetero_dof)
#>                          m_hetero      m_hetero_sum      m_hetero_dof
#> Dependent Var.:                 y                 y                 y
#>                                                                      
#> (Intercept)     6.526*** (0.4307) 6.526*** (0.4307) 6.526*** (0.4292)
#> x1               -0.2234 (0.1414)  -0.2234 (0.1414)  -0.2234 (0.1409)
#> _______________ _________________ _________________ _________________
#> S.E. type       Heteroskeda.-rob. Heteroskeda.-rob. Heteroskeda.-rob.
#> Observations                  150               150               150
#> R2                        0.01382           0.01382           0.01382
#> Adj. R2                   0.00716           0.00716           0.00716
```

So now the behavior is much more in line with what one expects. 

So that should solve the request I guess??
