### ISSUE TITLE
predict with interactions and newdata, when observations exceed 50000

### ISSUE THREAD

**Issue by benzipperer** [lrberge/fixest#115]
Hi, I love your package, thank you!

I'm having a little trouble getting predict.fixest with newdata to produce anything other than NA's when using interactions of fixed effects **and** when observation counts exceed 50000. Do you have any insight? 

Here's a silly example:
```r
library(tidyverse)
library(fixest)

my_data <- bind_rows(trade, trade)
my_data_50k <- head(my_data, 50000)

predict_full <- feols(Euros ~ log(dist_km) | Origin^Product, data = my_data) %>% 
  predict(newdata = my_data)

predict_50k <- feols(Euros ~ log(dist_km) | Origin^Product, data = my_data_50k) %>% 
  predict(newdata = my_data_50k)
```
Then
```r
all(is.na(predict_full))
[1] TRUE

all(is.na(predict_50k))
[1] FALSE
```

**Comment by lrberge** [comment]
Hey, I'm glad you like it!

That's a perfectly normal behavior! Here's the explanation. 

I use two different ways to combine two or more fixed-effects in the package: a) by coercing them with `paste()`, and b) by applying a numerical trick that I won't detail (you can look in the code!). 

The two methods have pros and cons:
  - a) it is very slow (try pasting vectors of millions of observations!), but it preserves the identity of the fixed-effects
  - b) it is extra fast, but you lose the identity of the fixed-effects

The only cases where you need the identity of the fixed-effects are in `fixef` to extract the fixed-effect coefficients, or in... `predict`.

Since the cases where we need the fixed-effects identity are rare, by default the fast method b) is applied when a) starts to be notably slow (it's an arbitrary threshold of 50k). Hence the threshold at which predict does not work for combined fixed-effects.

The argument `combine.quick` governs that behavior during the estimation. Use `combine.quick = FALSE` to get the behavior a) triggered and then predict should work.

----

That said, when `predict` would not work, an error message should appear explaining how to proceed to make it work. 
And... it did not appear.... (It's because I changed at some point how I would store the FEs names but forgot to update this particular code.)

Now I fixed this bug, the error message should pop! 

```R

# The error message you should have had
est_full = feols(Euros ~ log(dist_km) | Origin^Product, data = my_data)
predict_full = predict(est_full, newdata = my_data)
#>  Error in predict.fixest(est_full, newdata = my_data) : 
#>   You cannot use predict() based on the initial regression since the fixed-effect 'Origin^Product' was combined 
#> using an algorithm dropping the FE values (but fast). Please re-run the regression using the argument 'combine.quick=FALSE'. 

# And now the fix:
est_full_bis = feols(Euros ~ log(dist_km) | Origin^Product, data = my_data, combine.quick = FALSE)
predict_full_bis = predict(est_full_bis, newdata = my_data)
head(predict_full_bis)
#> [1] 131164073  85853622 275298274 100932455 146909572  92176040
```
----

I hope I was clear! :-)

Thanks again for filing the issue, you helped uncover a bug!

**Comment by benzipperer** [comment]
Thank you, this is perfectly clear! I should have seen the documentation for combine.quick but missed it. I think I searched for "50000" rather than "50,000" :smile:

Thanks again. I really appreciate your excellent package.
