### ISSUE TITLE
coefplot and interacted IV

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#124]
Coefplot does not seem to find any of the IV coefficients:

First in this version it seems like the problem is that there is only one variable found (x1):

```
data(base_did)
base_did$takeup <- rbinom(nrow(base_did), 1, 0.5)
est_did = feols(y ~ x1 | id + period | i(takeup, period, 5) ~ i(treat, period, 5), base_did)
coefplot(est_did)
```

```
Error in grepl(root_interaction, all_vars, fixed = TRUE) : 
  invalid 'pattern' argument
```

Cause when I instead run this it shows a coefplot but only with the control variables:

```
est_did = feols(y ~ i(x1, period) | id + period | i(takeup, period, 5) ~ i(treat, period, 5), base_did)
coefplot(est_did)
```

<img width="383" alt="Screen Shot 2021-04-07 at 10 20 17" src="https://user-images.githubusercontent.com/736668/113834208-dcc34d80-978a-11eb-956d-731ff869b7d3.png">

```
> coef(est_did)                                 
 fit_takeup:period::1  fit_takeup:period::2  fit_takeup:period::3  fit_takeup:period::4  fit_takeup:period::6  fit_takeup:period::7  fit_takeup:period::8  fit_takeup:period::9 
          19.83575653            9.11872814            0.16973539           -9.14475162           28.59971489           65.20626196         -112.35626421          -50.04440551 
fit_takeup:period::10          x1:period::1          x1:period::2          x1:period::3          x1:period::4          x1:period::5          x1:period::6          x1:period::7 
         129.42082551            0.92743328            0.80831986            0.65534223            1.38868377            1.30319582            0.30907614            2.34526755 
         x1:period::8          x1:period::9         x1:period::10 
          -0.76022618            0.07987883            0.54497292 
```

Trying to keep only `fit_takeup` does not help:

```
coefplot(est_did, keep = "fit_takeup")
```

<img width="471" alt="Screen Shot 2021-04-07 at 10 22 20" src="https://user-images.githubusercontent.com/736668/113834446-2449d980-978b-11eb-9fd2-aeb58ca582df.png">

same result for `coefplot(est_did, drop = "x1")`.

**Comment by lrberge** [comment]
Thanks for the report!

It's not just a bug, it's a deep problem of how `coefplot` deals with coefficients and in particular with interactions. It also has to deal with the use of `i()` within estimations. 

All this is pretty intricate and the way I deal with this at the moment has many shortcomings. But in the short/mid run I'll overhaul completely how `i()` works internally within `fixest` estimation and this will facilitate the interaction with `coefplot`.

So I cannot "fix" this now in `coefplot` because I'll later break the changes for a new architecture. 

So => no solution in the short run, sorry. But I'll fix it at some point.

**Comment by adamaltmejd** [comment]
Looking forward to it! Thanks again for all your work.

**Comment by adamaltmejd** [comment]
Do you have any suggestions for how to best extract IV coefs and confidence intervals from the feols object meanwhile?

**Comment by lrberge** [comment]
Oh sorry! I was too much focused on the first bug!!!

Just use `only.inter = FALSE`, because by default `coefplot` focuses only on interactions if it finds one. Using your example:

```R
data(base_did) ; base = base_did ; set.seed(1)
base$takeup <- rbinom(nrow(base), 1, 0.5)
est_did = feols(y ~ x1 | id + period | i(takeup, period, 5) ~ i(treat, period, 5), base)

coefplot(est_did, only.inter = FALSE)

```

This leads to the following graph, with no coefficient removed:
![image](https://user-images.githubusercontent.com/43536394/114001494-48c1b680-985c-11eb-8c8d-4c8dffae5e44.png)

Note that there is an automatic grouping of the coefficients. It can be turned off with `group = NULL`.

Now a few more examples with your second estimation (the calls are in the titles):
```R
est_did_bis = feols(y ~ i(x1, period) | id + period | i(takeup, period, 5) ~ i(treat, period, 5), base_did)
```

![image](https://user-images.githubusercontent.com/43536394/114002646-588dca80-985d-11eb-9fca-5a8b8ae723c8.png)

Note that I've just added user-defined default values for `only.inter`. So now if you run `setFixest_coefplot(only.inter = FALSE)`, you won't need to use this argument in future `coefplot` calls.

**Comment by adamaltmejd** [comment]
Awesome! Thanks!

**Comment by lrberge** [comment]
Actually, it should be fixed now. I'm closing.
