### ISSUE TITLE
when does etable show the Co-variance row?

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#127]
I could not figure out when etable shows the Co-variance row. In the example below, table1 and table2 do not show the Co-variance row while table3 does. 

```
data(iris)

model1 <- feols(Petal.Length ~ Sepal.Length, se = "hetero", data = iris)
model2 <- feols(Petal.Length ~ Sepal.Length|Species, se = "hetero", data = iris)
model3 <- feols(Petal.Length ~ Sepal.Length|Species, cluster = ~Species, data = iris)

table1 <- etable(model1, model2,
       title = "xyz", drop = "Intercept", digits = "r3", digits.stats = "r3",
       coefstat = "tstat", fitstat = ~n + ar2,  
       tex = TRUE,
       style.tex = style.tex(main = "aer", yesNo = c("Yes", "No")))

table2 <- etable(model3,
       title = "xyz", drop = "Intercept", digits = "r3", digits.stats = "r3",
       coefstat = "tstat", fitstat = ~n + ar2,  
       tex = TRUE,
       style.tex = style.tex(main = "aer", yesNo = c("Yes", "No")))

table3 <- etable(model1, model2, model3,
       title = "xyz", drop = "Intercept", digits = "r3", digits.stats = "r3",
       coefstat = "tstat", fitstat = ~n + ar2,  
       tex = TRUE,
       style.tex = style.tex(main = "aer", yesNo = c("Yes", "No")))


```

**Comment by lrberge** [comment]
It pops when there are at least two models with different types of VCOV. 

Actually, the inconsistency is salient because of the `style("aer")`. In the default style you have one line at the bottom of the table stating the type of VCOV. But of course it only works when all models have the same type of VCOV. That's why when 2+ models have a != VCOV, the line at the bottom disappears and the extra row stating each model's VCOV appears.

I don't think there's an option to add/remove that row => I think I'll add it since it can be a problem in the `aer` style. But so far if you want you can catch it and remove it with the `postprocess.tex` option.

**Comment by lrberge** [comment]
Hi! Finally, I've added a new argument `se.row` to handle when the row should pop.

Thanks for the comment, that was needed.

**Comment by waynelapierre** [comment]
This package is going to be the most widely used R package in the corporate finance area. I saw many people promoting it in various economics & finance communities. Great work!
