### ISSUE TITLE
etable inconsistency

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#133]
Hi again,

I encountered a particular inconsistency when asked `etable` to keep only selected coefficients using the `keep` argument.
While I successfully drop every coefficient that does not match the condition in when `tex=FALSE`, I get an error when setting `tex` to `TRUE`.

Below you can find an MWE

```
library(fixest)

data(base_did)

est_did1 = feols(y ~ x1 + post:treat | id + period, base_did)
est_did2 = feols(y ~ post:treat | id + period, base_did)

etable(est_did,keep = "post x treat")
etable(est_did,keep = "post x treat",tex = TRUE)
etable(est_did,tex = TRUE)

# Other stuff that I tried:
etable(est_did,keep = "post $\times $ treat",tex = TRUE)
etable(est_did,keep = "post:treat",tex = TRUE)
```

* I'd like to elaborate on why I find this consistency important. 
When I regularly work on a code in R and want to see the results, I usually want to set `tex` to false to see it in the console. This works quite flawlessly in "stargazer," for example. 

Also, since I'm not a latex master, nor table master, it is easier for me to run stable with `tex=FALSE` until I get the desired results and save it to tex only afterward. When `Tex=false` and `tex=TRUE` act so differently, I have to save the tex file, compile it, then edit it again, this process is way more complicated.

**Comment by lrberge** [comment]
Hi, the cause of this problem is that the variables names are relabeled, that is the original `post:treat` variable becomes: 
 - `post x treat` in `tex = FALSE`
 - `post $\\times$ treat` when `tex = FALSE`

The argument `keep` takes in regular expressions. So `keep = "post $\times $ treat"`  would never work, its regex counterpart being `"post \\$\\\\times \\$ treat"` (but actually with regular expressions you don't need to type all that, see below). I suggest you to learn regular expressions since they are extremely powerful tools (see [here](https://regexone.com/)). 

So one solution is to provide a valid regular expression that works on both displays. 

Another solution is to request `keep` to apply to the original name. You can do that by using `%` as the first character: `keep = "%post:treat"`. That's in the documentation section detailing [`keep`/`drop`/`order`](https://lrberge.github.io/fixest/reference/etable.html#arguments-keep-drop-and-order).

Here are examples:
```R
#
# using a regex that works for both
#

etable(est_did1, keep = "po.+eat", tex = FALSE)
#>                          est_did1
#> Dependent Var.:                 y
#>                                  
#> post x treat    4.851*** (0.4552)
#> Fixed-Effects:  -----------------
#> id                            Yes
#> period                        Yes
#> _______________ _________________
#> S.E.: Clustered            by: id
#> Observations                1,080
#> R2                        0.53213
#> Within R2                 0.36871

etable(est_did1, keep = "po.+eat", tex = TRUE)
#> \begin{tabular}{lc}
#> \tabularnewline\midrule\midrule
#> Dependent Variable:&y\\
#> Model:&(1)\\
#> \midrule \emph{Variables}&  \\
#> post $\times $ treat&4.851$^{***}$\\
#>   &(0.4552)\\
#> \midrule \emph{Fixed-effects}&  \\
#> id & Yes\\
#> period & Yes\\
#> \midrule \emph{Fit statistics}&  \\
#> Observations & 1,080\\
#> R$^2$ & 0.53213\\
#> Within R$^2$ & 0.36871\\
#> \midrule\midrule\multicolumn{2}{l}{\emph{Clustered (id) standard-errors in parentheses}}\\
#> \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
#> \end{tabular}

#
# Accessing the original variable name
#

etable(est_did1, keep = "%post:treat", tex = FALSE)
#>                          est_did1
#> Dependent Var.:                 y
#>                                  
#> post x treat    4.851*** (0.4552)
#> Fixed-Effects:  -----------------
#> id                            Yes
#> period                        Yes
#> _______________ _________________
#> S.E.: Clustered            by: id
#> Observations                1,080
#> R2                        0.53213
#> Within R2                 0.36871

etable(est_did1, keep = "%post:treat", tex = TRUE)
#> \begin{tabular}{lc}
#> \tabularnewline\midrule\midrule
#> Dependent Variable:&y\\
#> Model:&(1)\\
#> \midrule \emph{Variables}&  \\
#> post $\times $ treat&4.851$^{***}$\\
#>   &(0.4552)\\
#> \midrule \emph{Fixed-effects}&  \\
#> id & Yes\\
#> period & Yes\\
#> \midrule \emph{Fit statistics}&  \\
#> Observations & 1,080\\
#> R$^2$ & 0.53213\\
#> Within R$^2$ & 0.36871\\
#> \midrule\midrule\multicolumn{2}{l}{\emph{Clustered (id) standard-errors in parentheses}}\\
#> \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
#> \end{tabular}
```
