### ISSUE TITLE
Feature Request: IV measures

### ISSUE THREAD

**Issue by 24thronin** [lrberge/fixest#140]
Hi Laurent,
First off let me say how much I appreciate the package you have achieved and continue to develop. It has already reduced the estimation time for one of my projects by several weeks.

Would it be possible to add the Sanderson and Windmeijer (2014) first stage F statistic as one of the standard IV outputs available? Since fitstat_register requires a scalar to be returned I would currently have to loop through and register separate statistics for each endogenous variable. Then the fitstat call becomes rather cluttered and non-standard.

I would like to add the SW F-stats for all of the endogenous variables under a single group heading like we can currently do for the built in ivf1 and ivwald1 statistic groupings. Is it possible to change fitstat and fitstat_register to accept from the function a vector or a list of lists of the form (label,stat,p,df,df1,df2,vcov) and a statistic group name? I think this would require changing the back-end of fitstat to loop through the outputs of user-defined functions and create sub-statistics.

This would be nice to have but I understand that it isn't the primary purpose of this package. 
Again thank you so much for the fantastic work.
John

**Comment by lrberge** [comment]
Hi John and thanks for the words :-) (Woo, several weeks saved, that's really great, thanks for letting me know!)

You're bringing a lot of good ideas here! I first created `fitstat_register` with simple statistics in mind, but adding sub stats is a very natural extension and should be there 100%. By the way I'll also add an `iv` argument, such that if `iv = 1`, the loop through each first stage regression will be done internally in `fitstat` so you don't have to bother doing it and can only focus on the statistic for a single estimation.

Once the new `fistat_register` is there it will be exceedingly easy to add new stats as built in. Since it seems that you've coded this statistic already, I would be very grateful if you mind submitting a PR such that the SW could join the crew. I'll write some guidelines on how to add new built-in stats but it should be very straightforward.

A word on the timeline: I think I can have it done in a few weeks (I have to finalize many things in the current master before that) but not before.

**Comment by 24thronin** [comment]
Hi Laurent,
Thanks for the response. I haven't coded the SW statistic yet. It is calculated by running two regressions for each endogenous variable in each specification. The first regression orthogonalizes the target endogenous variable to the variation in other endogenous variables explained by the instruments. The second regression takes the estimated residuals and estimates their relationship to the instruments. The SW metric is the F-stat of the instruments in the second regression. A basic 5 line stata script is available in the appendix at the end of their paper (https://www.sciencedirect.com/science/article/pii/S0304407615001736).

Since 2 regressions are required for each endogenous variable and each regression specification I think this may slow down the feols if the user isn't careful so it may be better to add it as an optional statistic. 

The only way I can think of getting this to work is to run it as a post-estimation command and save the statistics in the model object. Then define a function that works with fitstat to retrieve the group of statistics (one for each endogenous variable). I can't work on this at the moment but I look forward to working on the SW statistic when the fitstat_register and fitstat objects are updated.

Note: When you create the "iv" option in fitstat_register it may be nice to be able to specify whether the statistic is intended to be associated with the 1st stage regressions, the 2nd stage regressions, or both.

All the best and thanks again for your excellent effort on this package.
John

**Comment by lrberge** [comment]
Hi John! Finally I've implemented a new version of `fitstat_register`. I did not implement the `iv` thing because there were too many caveats and limitations. I hope the example in the help page is clear enough (I had to rush a bit and didn't explain every possibility though), but your use case should be covered. Let me know!

**Comment by 24thronin** [comment]
Thanks Laurent. I will take a look at the new function and see if I can get this metric up and running soon.
All the Best!

**Comment by lrberge** [comment]
Hi John, did it work?
