### ISSUE TITLE
esttex allow a space between rows?

### ISSUE THREAD

**Issue by SebKrantz** [lrberge/fixest#141]
Hi Laurent, I've just used esttex for the first time. Overall nice work! I just have very small ideas for enhancement, I always like to have a space between coefficeint rows e.g. by using `\\\\` instead of `\\` after the standard errors:
```
(Intercept)&0.0678$^{***}$ &    &    & 0.0752$^{***}$ &    &   \\
  &(0.0088) &    &    & (0.0038) &    &   \\\\
myvar &-1.488$^{**}$ & -5.526$^{***}$ & -5.952$^{**}$ & -0.1546$^{*}$ & -0.8395$^{***}$ & -0.6364$^{**}$\\
  &(0.5558) & (1.892) & (2.449) & (0.0901) & (0.2898) & (0.2812)\\\\
```
I would also be good to print the table more cleanly putting spaces between items and & e.g. (Intercept) & 0.0678, also for the statistics below (R2 etc). Finally it would be very nice to be able to round the stats (R2 etc.) to a number of digits (separate from the coefficient rounding). Doing this would spare me time going over the tables again manually adding spaces and rounding numbers, but I understand that might not be a top development priority.

**Comment by lrberge** [comment]
Hi Sebastian! 

For the first request: that's very specific! ;-) The problem of this issue is that it's pretty involved to do it out of the function so it should be covered inside. Sure I can add it, but I first have to find a proper argument name, I'll let you know! 

For the spaces for readability: good idea (I actually don't read tex directly since I'm a Lyx user so I never was annoyed).

For the third suggestion: that's covered already! ;-) It should be in the current version: arguments `digits` and `digits.stats`.

**Comment by SebKrantz** [comment]
Hi Laurent, thanks a lot! I would actually think that many coefficient tables in papers have some space between coefficient rows. Stargazer I think also does it. Sorry for the late response, traveling these days. Best regards!
