### ISSUE TITLE
Segmentation fault when nthreads>2 in feglm

### ISSUE THREAD

**Issue by mangelett** [lrberge/fixest#146]
Hi,
We estimate a model using the function feglm and we try to sue the nthreads option to speed-up the estimation. The model is estimated normally if the option is not used or if nthreads is fixed to 2. When we fix nthreads greater than 2, the code produces a segmentation error and R aborts. The error  can be  a "memory not mapped"  error or a "double free or corruption " error. Please find the [logfile](https://github.com/lrberge/fixest/files/6494716/logfile.txt).

Thank in advance,

**Comment by lrberge** [comment]
Hi, thanks for the report. Unfortunately this is specific to your setup. Could you send a reproducible example (via email for instance)? Ideally with a smaller dat set. Otherwise it's too difficult for me to debug because the absence of generality.

**Comment by lrberge** [comment]
Hi, it was the same as #157 -- and it was indeed because of a parallel section.
I still don't understand why it didn't work... Anyway, now the bug should be fixed.

**Comment by lrberge** [comment]
Thanks for reporting, it was a pity I couldn't replicate though.

**Comment by lrberge** [comment]
OK, now I understand what the problem was. It is because I updated a vector in parallel, there was no race condition because the updated values of the vector were fixed and not dependent on its past values. 
Yet I did update, not a regular vector, but a **boolean** vector! These are specific beasts that don't store the values of each element in a separate cell in memory. They use a specific scheme for storage that group values together such that when we update an element, some other parts of the vector may change. This in turn creates a race condition. 
That was tricky to spot, I won't get caught again!

By the way, could you check that the fix worked? Thanks!

**Comment by mangelett** [comment]
Hi,

Thank you for fixing the bug. I tested the github version on my Linux systems and it works when I set nthreads greater than 2.

**Comment by lrberge** [comment]
Merci d'avoir vérifié ! et désolé de n'avoir pu le résoudre la première fois.
