### ISSUE TITLE
use all threads by default

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#147]
Why not make the fixest package use all threads by default?

**Comment by lrberge** [comment]
That's because multi-threading efficiency is not 1:1. The marginal value of an additional thread is decreasing with the nber of threads. It's usually good practice to leave resources for other programs to run especially that using all threads isn't (in most cases) optimal.

There is an exception though: when there are MANY variables and the fixed-effects convergence is difficult. There the efficiency is almost 1:1, but that's not the most common case.

In any case you can still set it via your .Rprofile with `library(fixest) ; setFixest_nthreads(0)`.
