### ISSUE TITLE
Custom .vcov for esttable like in summary

### ISSUE THREAD

**Issue by kylebutts** [lrberge/fixest#150]
Currently the .vcov option for esttable only allows a custom function for creating standard errors. Is it possible to manually pass a .vcov matrix the same way it is possible for summary? That would be really great help!

**Comment by kylebutts** [comment]
I'm going to close this issue with a note, because I discovered a solution.

Calling summary with .vcov creates a new fixest object with cov.scaled and se objects using the custom .vcov matrix.

Therefore, you can call fixest::esttable on the fixest object created with summary(fixest_obj, .vcov = custom_vcov)

**Comment by lrberge** [comment]
Indeed, I didn't implement the passing of VCOV matrices in `etable` since it is built for reporting several models. To pass matrices if there are svl models, one would have to pass a list of matrices in `.vcov` that matches each model: this is too impractical and error prone.

Great you found out a solution! :-)
