### ISSUE TITLE
Multiple factors in new i()

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#152]
Hey!

Thanks for the update, lots of stuff I've been looking forward to :). Having some trouble with the new `i()` though. What is your suggested way of running multiple interactions? Seems the only thing working is creating a new factor:

```
data(base_did)

# Does not work anymore
feols(y ~ i(period, i.treat, x1), base_did)
# Error in feols(y ~ i(period, i.treat, x1), base_did) : 
#   Evaluation of the right-hand-side of the formula raises an error: in i(factor_var = period, var = i.treat, ref = x1):
#  In argument 'ref', the values don't match any value of 'factor_var'.

# Works but output() gets cluttered
feols(y ~ i(paste(period, treat), x1), base_did)

# Does not work but would make sense (also error message says nothing about nested i() not being allowed)
feols(y ~ i(i(period, i.treat), x1), base_did)
# Error in feols(y ~ i(i(period, i.treat), x1), base_did) : 
#   Evaluation of the right-hand-side of the formula raises an error: operations are possible only for numeric, logical or complex types
```

**Comment by lrberge** [comment]
Hi Adam! Yeah, you're pointing to a strict regression, that's not possible any more to do that within `i()`.

The reason I removed the third argument for interactions was threefold. First the internal code was hard to digest with the three possible interactions, so I dropped one when I tidied it up and improved it. Second, I found it very confusing from the user-side (especially new users) to have these three arguments. By keeping it lean with just two arguments, the first always a factor, makes it much more intuitive I think. Third, I really thought nobody would be using triple interactions within `i()`: you proved me wrong :-) 

So one has to resort to the old `R` way (which is pretty nice by the way :-)):
```R
feols(y ~ x1:i(period, i.treat), base_did)
#> OLS estimation, Dep. Var.: y
#> Observations: 1,080 
#> Standard-errors: Standard 
#>                       Estimate Std. Error t value Pr(>|t|))    
#> (Intercept)           1.999500   0.149937 13.3360 < 2.2e-16 ***
#> x1:period::1:treat::0 0.963380   0.227675  4.2314   2.5e-05 ***
#> x1:period::1:treat::1 0.808834   0.211452  3.8251  0.000138 ***
#> x1:period::2:treat::0 1.061200   0.213309  4.9747  7.62e-07 ***
#> x1:period::2:treat::1 0.896575   0.205207  4.3691   1.4e-05 ***
#> x1:period::3:treat::0 1.064300   0.241338  4.4099   1.1e-05 ***
#> x1:period::3:treat::1 0.530285   0.202285  2.6215   0.00888 ** 
#> x1:period::4:treat::0 1.417500   0.251633  5.6330  2.27e-08 ***
#> ... 13 coefficients remaining (display them with summary() or use argument n)
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 4.8535   Adj. R2: 0.262364
```

One question you could ask: Why using `i(factor_var, continuous_var, ref)` instead of `i(factor_var, ref):continuous_var` then? Well there's no reason ;-D, there's a tiny speedup in the first command, but not much more, it's just a matter of taste.

By the way, what do you think about the `i.` prefix? It's non-standard `R`, I don't know if I should keep it... 

And I agree the error message is not informative, but it's a bit of work to correct that. I'll see what I can do!

**Comment by adamaltmejd** [comment]
Haha, never underestimate the users' ability to find edge case uses for whatever you build ;). I think the changes to `i()` make perfect sense and I would agree its completely reasonable to limit the number of interactions (either that or go full `...` and allow as many as one wants). 

Thanks, totally forgot about base-R interactions :).

Re `i.` and the design of `i()` in general, since you asked for my opinion I would probably prefer standard R functional notation. Using "i." seems like it invites different kinds of problems both in terms of bugs and user understanding. But the problem partly stems from the fact that `i()` is short for interaction making `i()` with one variable only seem unintuitive. But isn't this really because you are using `i()` to do two things (1) interaction (2) set factor reference. Would one option perhaps be to divide this into two separate functions? Perhaps using `ref(var, ref)` and `i(var1, var2)` so that if you want to use an interaction with a factor with a specific reference you would have to run `i(ref(var1, ref), var2)`? Breaking again but it would be my preferred way of doing this :).

**Comment by lrberge** [comment]
Thanks for giving your honest opinion Adam!

I actually really like the name `i()`. In general I think functions doing something extremely frequent (like transforming into a factor) should have a short name (and for some reason I hate typing `factor()`!). And it's in fact identical to the Stata `i.` so it's intuitive at least for Stata users (which I occasionally am). 
But I agree that the fact that the help page defines it as the short alias for `interact()` is confusing, so I've just removed `interact()` completely (and I guess nobody used it anyway [but I may be wrong ;-)]). In the future I'll rewrite the doc to make it clearer.

I've tried to implement nested `i()`s, like `i(x1, i(x2))`, but the fact that I do a lot of non-standard evaluations make it devilishly difficult, although I think it's a nice idea that I may implement in (the far) future. 

On having a `...` argument with any number of variables to interact, why not but then one has to find out a nice way to implement the references. Further, I've never used/needed beyond two interactions, maybe when I need to do it I'll find a solution (it's really too costly to implement stuff that you don't use).

I'm rushed by CRAN to resubmit, otherwise the package will be removed tomorrow.... So the interactions with `i()` will stay that way, but I'm still not 100% satisfied, the discussion is still open!

**Comment by adamaltmejd** [comment]
Makes sense, and I do agree that i() is nice and short. But what about separating the reference part into a function ref() that way nesting would be easier: eg: `i(x, ref(t, 0))` and it would be easier to implement `...`. Agree that its very low priority though, especially since one can always create interactions with `paste()` or similar.
