### ISSUE TITLE
add glmmTMB to benchmark 

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#153]
It would be interesting to add the R package glmmTMB to your benchmark. 
https://github.com/glmmTMB/glmmTMB

**Comment by lrberge** [comment]
Hi, I didn't know about that package. Its generality is really awesome! That's quite impressive.

But it is geared towards different kind of models and hence the price to pay is that they are a bit less efficient for the specific models dealt with in `fixest`. 

Here's a simple benchmark with no fixed-effects:

```R
library(glmmTMB) ; library(fixest)
data(trade)
system.time(a <- glmmTMB(Euros ~ log(dist_km), trade, family = poisson))
#>    user  system elapsed 
#>    0.39    0.00    0.39 
system.time(b <- fepois(Euros ~ log(dist_km), trade))
#>    user  system elapsed 
#>    0.07    0.00    0.04 
```

So it's about 10 times slower for this simple setup, hence I won't include it in the benchmark (since the discrepancy would only increase with large fixed-effects). Further it would be a bit unfair for `glmmTMB` since it deals with a much broader set of models.
Otherwise, thanks for the pointer!
