### ISSUE TITLE
Warning when running IV estimation using csw0

### ISSUE THREAD

**Issue by fabrizioleone** [lrberge/fixest#160]
Hi,

First of all, thanks a lot for your fabulous package. It's truly great.

I am opening this issue because I noticed that `feols` throws the following warning when running IV estimation using the  `csw0` function:

> In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation

Please find below a minimal example to reproduce this issue using `fixest` 0.8.4.

```R
library(fixest)
data("mtcars")

dt <- mtcars

feols(mpg ~ csw0(disp, hp), dt)
feols(mpg ~ csw0(disp, hp) | qsec ~ carb, dt)
```

You will see that the last line throws the warning above. By contrast, if you simply run

````R
feols(mpg ~ disp + hp, dt)
feols(mpg ~ disp + hp | qsec ~ carb, dt)
````

you will get no warning. Am I maybe using the `csw0` function poorly?
 
This example is obviously purely illustrative. I am not trying to interpret the coefficients. 

Any help is much appreciated.  Thanks a lot once again for the great work.

**Comment by lrberge** [comment]
Hi Fabrizio! 

You're doing it right! Although worrying, these warnings are innocuous: it's due to a non-trivial nested call to `try()` for a missing argument (that's a bit technical sorry!) -- it does not affect the results at all, it was only part of the argument checking. 
It occurred not in the estimation but when `summary` was (implicitly) called.

So I've added a default to an argument and now it's gone :-)
Thanks again!

**Comment by fabrizioleone** [comment]
Hi Laurent,

Many thanks! Great as usual.

Best,

Fabrizio
