### ISSUE TITLE
Error parsing formula with function call specified as package::function

### ISSUE THREAD

**Issue by kbrevoort** [lrberge/fixest#162]
I've noticed a minor bug when calling a function inside a formula.  Explicitly referencing the package that the function is in (for example, calling _splines::bs()_ instead of just _bs()_) can generate an error.  Obviously, this problem can be avoided by not using explicit package references so it's a very minor bug.  

Here's a quick example

```
library(fixest)
library(splines)

# Using the {splines} basis functions in the formula statement works
feols(mpg ~ bs(wt, df = 3),
      data = mtcars)

#> OLS estimation, Dep. Var.: mpg
#> Observations: 32 
#> Standard-errors: Standard 
#> (Truncated)

# When an explicit reference to {splines} is made, an error is returned
feols(mpg ~ splines::bs(wt, df = 3), 
      data = mtcars)

#> Error in feols(mpg ~ splines::bs(wt, df = 3), data = mtcars) : 
#>   Error in the interaction in the RHS of the formula:
#> Problem in the interaction of the formula: Error in
#> splines::bs(wt, df = 3) : unused argument (df = 3)
```

**Comment by lrberge** [comment]
Hi, it's actually not (really) a bug, it's just that I introduced (long ago) a very weird syntax shortcut for interactions: `var::var_as_factor(reference)` (I wanted to provide a shortcut to `var:factor(var_as_factor)` so I introduced that -- then I later introduced references). If you use the previous syntax, it's like using `i(var, factor, reference)`.

Of course this syntax necessarily breaks the regular `package::function` syntax. But it was a bad design decision and I think I will remove it in the next update (which already contains breaking changes) so that the kind of problem you refer to will be gone.

I'll let you know.

**Comment by lrberge** [comment]
OK, I removed the possibility to use the `var::factor` shortcut, now `::` can be used normally:

```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

feols(y ~ stats::poly(x1, 2), base)
#> OLS estimation, Dep. Var.: y
#> Observations: 150 
#> Standard-errors: IID 
#>                     Estimate Std. Error t value  Pr(>|t|)    
#> (Intercept)           5.8433   0.066922 87.3160 < 2.2e-16 ***
#> stats::poly(x1, 2)1  -1.1884   0.819622 -1.4499  0.149214    
#> stats::poly(x1, 2)2  -1.4158   0.819622 -1.7274  0.086204 .  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 0.811384   Adj. R2: 0.020291
```
