### ISSUE TITLE
How to implement threeway interactions in feols?

### ISSUE THREAD

**Issue by jsoeldi** [lrberge/fixest#166]
Hey,

first of all thank you very much for the package, it's fantastic. 
I have a general question and could not find any hint about it in the documentation. To include twoway interactions in my feols regression I use the recommended "i(factor_var, var, ref, keep, ref2, keep2, ...)". 

The problem is that the documentation says nothing about how to deal with threeway interactions, so I tried the conventional var1:var2:var3, which works within feols, however I cannot specifiy any baseline category. Is there a way to do it?

Thank you very much! 

Best,
Julian

**Comment by lrberge** [comment]
Hi and thanks for the words :-)

Using `i()` can be a bit tricky when you want to combine in complex ways. It's still work in progress, I haven't yet found a design that cope with all the cases.

In you situation, where I assume at least one variable is numeric, you can do as follows:
```R
set.seed(1)
base = iris
names(base) = c("y", "x1", "x2", "x3", "f1")
base$f2 = rep(letters[1:5], 30)

# two factors, 1 numeric
est = feols(y ~ x1 + i(f1, f2, ref = "virginica", ref2 = "b"):x2, base)
etable(est)
#>                                               est
#> Dependent Var.:                                 y
#>                                                  
#> (Intercept)                     4.782*** (0.4602)
#> x1                              0.4885** (0.1505)
#> x2 x f1 = setosa x f2 = a     -0.8690*** (0.1508)
#> x2 x f1 = setosa x f2 = c      -1.149*** (0.1627)
#> x2 x f1 = setosa x f2 = d     -0.9865*** (0.1517)
#> x2 x f1 = setosa x f2 = e     -0.9286*** (0.1450)
#> x2 x f1 = versicolor x f2 = a    -0.0471 (0.0498)
#> x2 x f1 = versicolor x f2 = c     0.0113 (0.0514)
#> x2 x f1 = versicolor x f2 = d    -0.0471 (0.0515)
#> x2 x f1 = versicolor x f2 = e   -0.0950. (0.0537)
#> _____________________________ ___________________
#> S.E. type                                Standard
#> Observations                                  150
#> R2                                        0.44319
#> Adj. R2                                   0.40739
```

Hope this helps!

**Comment by jsoeldi** [comment]
Hey, 

thank you very much! I actually solved it like that, but I guess it should deliver the same results:

I am estimating a Dif-in-Dif model, with the dependent variable being unemployed (0 or 1) and the diff-in-diff estimator ist the following interaction (month, a covid policy stringency index and race).

+i(Date_20200401*Stringency_Index_high, race, ref = "White", keep = c("Asian", "Black", "hispanic"))

Please let me know if it is not the same or if it can cause problems! :)

Thank you!

**Comment by jsoeldi** [comment]
I have an additional question with that: In the basic lm() function when I use three-way interactions, the model output automatically includes the lower order interactions. When I use the i() function in feols, this is not the case. I am wondering if this is automatically done in the background or has to be specified manually. I did it manually and the results were different. Therefore, I am confused if I have to specify them manually or if it distorts the results....Thank you!

**Comment by lrberge** [comment]
Hi, sorry I didn't have the time to come back to you earlier.

Regarding your previous post, a few comments for clarifications:
 - usually `ref` should not be used along with `keep`. Eg in your example only `c("Asian", "Black", "hispanic")` would be kept anyway so `ref` is here somewhat redundant. I created the two arguments because sometimes it is shorter to write which to keep instead of which to drop. In this case `ref = "White"` should be sufficient. 
 - the function `i()` currently accepts only two values to be interacted, so unfortunately the code `i(Date_20200401*Stringency_Index_high, race, etc...` would not work as expected. One really needs to add the numeric variable out of the function.

Regarding your new comment. Yes, you're right, in regular interactions with factors in `lm` all the sub elements are added and, unfortunately, _this is not possible with i()_. But nothing is done under the hood :-) they're just not there! And you can still use the regular `lm`-style interactions, but without the dynamic reference allowed by `i()` then.
This is a strong limitation of `i()` which was created for single interactions with factors used as fixed-effects in mind. There is no plan to extend it because allowing `lm`-style factor interactions is actually surprisingly difficult.

So sorry, no simple way out of your problem :-(

**Comment by jsoeldi** [comment]
Hi,

thank you very much for your reply. Yes I changed the three-way interaction to the one you proposed. But in the end, if I include the corresponding two-way interactions manually, the result should be the same as in the conventional $lm$ right? 
What is also surprising is that the function i(factor_var, var, ref, keep, ref2, keep2, ...) works different the suggested in the documentation. So basically on my machine it is i(var, factor_var, ref, ....), the factor var to which the ref argument relates is the second, not the first term and it seems to work fine.

**Comment by lrberge** [comment]
Yes, the results should be the same, but then it may differ based on which variable is taken out as reference. If the latter has been done with regular factors `lm`-style, sometimes when a variable has many categories, it may be very hard to spot. But there is no reason it should differ.

On the latter point it is likely a version issue. Version 0.9.0 (released a few weeks ago) introduced a swapping of the first two arguments of `i()` (a major breaking change).

**Comment by jsoeldi** [comment]
Perfect, thank you very much. I will just proceed with setting the factor level to "white" and the conventional Date*Stringency_Index*race and it calculates all the interactions automatically. The feols package is way faster, but the results are the same as in the lm model! :)

**Comment by lrberge** [comment]
Great! :-) Closing then!
