### ISSUE TITLE
Error or Feature Request or Advice - Poolsize a la reghdfe

### ISSUE THREAD

**Issue by cseveren** [lrberge/fixest#168]
First of all - Excellent package, thanks! I'm working on implementing fixed effects on large dataset (csv is about 7GB) with many fixed effects and a good number of covariates, and my machine has 48GB of RAM. I have been getting errors similar to:
```
Error in feols(ln_trantime ~ i(d_black, year_bin) + ..demog_yr | czone_year_bin, 
  Evaluation of the right-hand-side of the fomrula raises an error: cannot allocate vector of size 129.4 Gb
```
when executing something like:
``` 
setFixest_fml(..demog_yr = ~i(female,year_bin) + i(educ_bin, f2=year_bin) + i(age, year_bin) + i(age2, year_bin) + i(d_marr, year_bin) + i(d_head, year_bin) + i(children, year_bin))
setFixest_nthreads(0.8)

TA.1 <- feols(ln_trantime ~ i(d_black, year_bin) + ..demog_yr
                 | czone_year_bin, data, 
                 cluster = "czone", weights = data$wt, lean = TRUE, mem.clean=TRUE)
```

As you can see, I'm concerned about overhead and memory usage, hence using the `lean` and `mem.clean` options. Nonetheless, I get the allocation error. 

One potential way around this that is mentioned in the documentation for `reghdfe` governing poolsize, and limits the number of variables that are simultaneously demeaned (I think) (unfortunately Stata runs out of memory and crashes as well...)  Is there an equivalent trick that I can utilize here? 

Alternatively, is it possible that altering either of the `lean` and `mem.clean` options could actually free up some memory (doubtful I know)? If not, do you have any other suggestions to limit exposure to such allocation crashes?

**Comment by lrberge** [comment]
Hi, thanks for using! 

The problem is simply that you're creating a gigantic design matrix because you have so many coefficients to estimate (the function `i()` creates lots of coefficients). There's no way around that.

My guess is that you don't need the standard-errors of all of them, most are controls. So you should put all the controls in the fixed-effects part of the formula. 

For example:
```R
feols(ln_trantime ~ i(d_black, year_bin) | czone_year_bin + year_bin[female, age, age2, etc...], data, etc...)
```

The syntax is explained in the dedicated [`feols` help section](https://lrberge.github.io/fixest/reference/feols.html#varying-slopes).
Doing so, the memory problem should be gone. Results (for `i(d_black, year_bin)`) will be identical. Let me know if it works (but again, there's nothing more I could do, it's not an algorithmic problem).

**Comment by grantmcdermott** [comment]
Chris, I should wait for Laurent to weigh in, but quickly: 

Which version of fixest are you using? The order for `i()` was recently swapped in the latest release (`v. 0.9.0`; see discussion in https://github.com/lrberge/fixest/issues/90).  Now it's `i(factor_variable, continuous_variable)`, whereas for earlier versions it was `i(continuous_variable, factor_variable)`. The reason I highlight this is because, depending on the version, you may be asking fixest to coerce a continuous variable into a factor... which is very computationally expensive and almost certainly not what you want. Again, not saying that this is definitely happening, but worth checking. 

(One quick way: Estimate your regression on a small subset of the data and see if the coefficients make sense.)

---

As to your pooling question, note that you can manually demean the variables. See the the `?demean` documentation for examples. I really doubt that the demeaning is what's causing the allocation error, but for posterity: Here's a adapted version that demeans two variables separately.

```r
data(trade)

base = trade
base$ln_dist = log(base$dist_km)
base$ln_euros = log(base$Euros)

# We center the two variables ln_dist and ln_euros
#  on the factors Origin and Destination
# GM: The doc example does them together, but here I'll do separately
# to illustrate.
X1 = demean(X = base[, "ln_dist"], f = base[, c("Origin", "Destination")])
X2 = demean(X = base[, "ln_euros"], f = base[, c("Origin", "Destination")])
base[, c("ln_dist_dm", "ln_euros_dm")] = cbind(X1, X2)

# Demean version
est_dm = feols(ln_euros_dm ~ ln_dist_dm, base)
# Regular FE version
est_fe = feols(ln_euros ~ ln_dist | Origin + Destination, base)

etable(est_dm, est_fe)
```

**Comment by cseveren** [comment]
Thanks for the support both! I think both issues were at play, both the large design matrix and the updated ordering of fixed effects. I hadn't realized there were such big updates since the last time I was using `fixest` only a couple months ago. 

BONUS <- I was able to run some pretty heavy models with lots and lots of data and lots and lots of fixed effects in about 30 minutes; with Stata's excellent `reghdfe` (which I do love and think is great) I ran into a wall, and the program continually crashed even with careful memory management. Nice work with this **excellent** package. Closing.
