### ISSUE TITLE
Fatal error with FeNmlm function

### ISSUE THREAD

**Issue by marissachilds** [lrberge/fixest#17]
Thanks for a really useful package. 

One error I've encountered is FeNmlm crashing R with a fatal error. I can reproduce this behavior with the example below. Thanks in advance for any help. 

library(dplyr)
library(magrittr)
library(fixest)

n_id = 800 
n_year = 8
b_true = 1
a_true = 0.5
set.seed(1001)
test_df = data.frame(id = rep(1:n_id, n_year),
                     year = rep(1:n_year, each = n_id)) %>%
  group_by(id) %>% 
  mutate(mu = rnorm(1, 0, 1)**2) %>% # generate id fixed effect
  ungroup %>%
  mutate(X = rnorm(n_year*n_id, 0, 1)**2,  # random X
               Z = rnorm(n_year*n_id, 0, 1)**2,  # random Z
               Y = rpois(n_year*n_id, mu*(1 + b_true*X)^a_true)*Z) # outcome Y

feNmlm(Y ~ log(Z) + log(1 + X) | id,  
       data = test_df,
       verbose = 1) # works perfectly

feNmlm(Y ~ log(Z)  | id,  
       data = test_df,
       NL.fml = ~ a*log(1 + X),
       NL.start = list(a = 0.5),
       verbose = 2) # reports that R encountered a fatal error and restarts`

**Comment by lrberge** [comment]
Hi, thanks a lot for the report ! This is a very BIG and nasty bug!

Fortunately easy to correct! It occurred only with non-linear RHS when some observations were removed (due to NAness or to perfect fit).

I've just updated the GH version, it should work now. 

Thanks a lot for the reproductible example, it made it very easy to solve.

**Comment by marissachilds** [comment]
Thanks so much for the speedy fix. Again, really useful package to be able to specify both non-linear RHS and multiple fixed effects.
