### ISSUE TITLE
Trying to group models, found different escaping rules for var.title and line.top in style.tex?

### ISSUE THREAD

**Issue by nhirschey** [lrberge/fixest#173]
Thank you for the nice package.

I am trying to put models into column groups using `\multicolumn`. I first tried by putting tex into `var.title`, but it kept escaping `&` to `\&` which caused tex errors. Eventually I found that I could use `line.top` because it did not cause this escaping issue.

I know that I am abusing these `var.title` and `line.top` options, but column groups are common in regressions. 

Thoughts:
1. Is the `var.title` escape rule too strict? Should it be like `line.top`?
2. At a minimum it would be nice to document the different escaping rules.
3. Given that model groups are common, perhaps a better resolution is to add a "model groups" option to style.tex. Something like extra.lines could work, but with the format model group name and then number of columns mimicking kableExtra such as `list("Model Group 1"=2,"Model Group 2"=1)`.

## Working example using `line.top`
```R
est = feols(c(Ozone, Solar.R,Wind) ~  poly(Temp, 2),airquality)
etable(est,tex=TRUE
       #,file=file.path(outTablesDir,"test.tex"),replace=TRUE
       ,style.tex = style.tex(line.top="\\toprule & \\multicolumn{2}{c}{A} & \\multicolumn{1}{c}{B}\\\\ \\cmidrule(lr){2-3}\\cmidrule(lr){4-4}"))
``` 
```
\begin{tabular}{lccc}
\toprule & \multicolumn{2}{c}{A} & \multicolumn{1}{c}{B}\\ \cmidrule(lr){2-3}\cmidrule(lr){4-4}
Dependent Variables:&Ozone&Solar.R&Wind\\
Model:&(1) & (2) & (3)\\
\midrule \emph{Variables}&   &   &  \\
(Intercept) & 42.14$^{***}$ & 185.2$^{***}$ & 9.958$^{***}$\\
  &(2.086) & (7.218) & (0.2548)\\
poly(Temp,2)1 & 272.4$^{***}$ & 317.2$^{***}$ & -19.89$^{***}$\\
  &(25.94) & (91.89) & (3.152)\\
poly(Temp,2)2 & 102.8$^{***}$ & -33.07 & -0.6379\\
  &(27.46) & (92.49) & (3.152)\\
\midrule \emph{Fit statistics}&  & & \\
Observations & 116&146&153\\
R$^2$ & 0.54422&0.07691&0.20997\\
Adjusted R$^2$ & 0.53615&0.06400&0.19943\\
\midrule\midrule\multicolumn{4}{l}{\emph{Normal standard-errors in parentheses}}\\
\multicolumn{4}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
```

![image](https://user-images.githubusercontent.com/5226115/124951799-98568080-e00b-11eb-86d0-ace17a7237d1.png)

## Broken example with var.title that causes `\&`

```R
etable(est,tex=TRUE
       #,file=file.path(outTablesDir,"test.tex"),replace=TRUE
       ,style.tex = style.tex(var.title ="\\toprule & \\multicolumn{2}{c}{A} & \\multicolumn{1}{c}{B}\\\\ \\cmidrule(lr){2-3}\\cmidrule(lr){4-4}"))

```
```
\begin{tabular}{lccc}
\tabularnewline\midrule\midrule
Dependent Variables:&Ozone&Solar.R&Wind\\
Model:&(1) & (2) & (3)\\
\toprule \& \multicolumn{2}{c}{A} \& \multicolumn{1}{c}{B}\\ \cmidrule(lr){2-3}\cmidrule(lr){4-4}&   &   &  \\
(Intercept) & 42.14$^{***}$ & 185.2$^{***}$ & 9.958$^{***}$\\
  &(2.086) & (7.218) & (0.2548)\\
poly(Temp,2)1 & 272.4$^{***}$ & 317.2$^{***}$ & -19.89$^{***}$\\
  &(25.94) & (91.89) & (3.152)\\
poly(Temp,2)2 & 102.8$^{***}$ & -33.07 & -0.6379\\
  &(27.46) & (92.49) & (3.152)\\
\midrule \emph{Fit statistics}&  & & \\
Observations & 116&146&153\\
R$^2$ & 0.54422&0.07691&0.20997\\
Adjusted R$^2$ & 0.53615&0.06400&0.19943\\
\midrule\midrule\multicolumn{4}{l}{\emph{Normal standard-errors in parentheses}}\\
\multicolumn{4}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
```

**Comment by lrberge** [comment]
Hi following your comments, I've made some changes.

Escaping is useful for stuff that vary (like variable names and common cell values) since doing it manually is a chore (we often forget) and it does not render so nicely when the table is printed in non-tex R. 
For the stuff that does not vary, it's OK. And the philosophy of `style.tex` is to contain elements of style (possibly complex tex stuff) and to be fixed across tables. Further, users tweaking Latex tables in that way are assumed to be well tex-aware. 
So I have suppressed any escaping occurring in the elements of `style.tex` (`var.title`, etc).

On the other hand I have extended the possibilities of the existing arguments. 
  1. I have renamed the argument `subtitles` into `headers` to increase clarity.
  2. `headers` accepts lists of the form `list("item1" = #item1, "item2" = #item2)` etc. For example `list("A"=2, "B"= 3)` will create a row with 2 times A and 3 times B. (Note that when the number of items is 1, you can omit the `= 1`.)
  3. you can "command" the placement with 3 special characters put at the start of the row title: "^" (top), "-" (mid, default) and "_" (bottom). Example: `list("_Group" = c("A", "B"))` will place the `Group` row at the bottom of the headers.
  4. you can add (as suggested) automatic *cmidrule*s by using the special command `:_:` in the row title. Example: `list(":_:Group" = list("A"=2, "B"= 3))` will create *cmidrule* groupings in the Group row.
  5. if you wish to disable latex escaping, use `:tex:` in the row title. Example in `list(":tex:Group" = c("A\\ & &", "B"))` nothing will be escaped.

Now to get back to your example, it can be easily obtained with `headers`:
```R
```{r}
est = feols(c(Ozone, Solar.R, Wind) ~  poly(Temp, 2), airquality)
etable(est, tex = TRUE, headers = list("^:_:" = list("A" = 2, "B")))
#> \begin{tabular}{lccc}
#> \tabularnewline\midrule\midrule
#>  & \multicolumn{2}{c}{A} & B \\ \cmidrule(lr){2-3} \cmidrule(lr){4-4}
#> Dependent Variables: & Ozone & Solar.R & Wind\\
#> Model: & (1) & (2) & (3)\\
#> \midrule \emph{Variables} &   &   &  \\
#> (Intercept) & 42.14$^{***}$ & 185.2$^{***}$ & 9.958$^{***}$\\
#>   & (2.086) & (7.218) & (0.2548)\\
#> poly(Temp)1 & 272.4$^{***}$ & 317.2$^{***}$ & -19.89$^{***}$\\
#>   & (25.94) & (91.89) & (3.152)\\
#> poly(Temp)2 & 102.8$^{***}$ & -33.07 & -0.6379\\
#>   & (27.46) & (92.49) & (3.152)\\
#> \midrule \emph{Fit statistics} &   &   &  \\
#> Observations & 116 & 146 & 153\\
#> R$^2$ & 0.54422 & 0.07691 & 0.20997\\
#> Adjusted R$^2$ & 0.53615 & 0.06400 & 0.19943\\
#> \midrule\midrule\multicolumn{4}{l}{\emph{IID standard-errors in parentheses}}\\
#> \multicolumn{4}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
#> \end{tabular}
```

The documentation of the new argument is [here](https://lrberge.github.io/fixest/reference/etable.html).

**Comment by lrberge** [comment]
Just a side note: please do not write things like "at a minimum". Please do remember that it's free software and I have to sacrifice my research to make it move forward.

Otherwise, thanks for the very clear issue.

**Comment by nhirschey** [comment]
My apologies, I was specifically trying to *not* come across as demanding. But conveying tone is tough, especially via the internet.

I have tried out the new header functionality. It is fantastic and accomplishes exactly what I was trying to do (stacked headers) in a very simple and intuitive way. Thank you for your hard work on this header feature and everything else with the library. I love the 0.10 vcov additions and stata comparisons.

> Escaping is useful for stuff that vary (like variable names and common cell values) since doing it manually is a chore 

Agreed, your choices here make sense. Thank you for the \section{Escaping special Latex characters}, this is very clear and helpful.

**Comment by lrberge** [comment]
I can't agree more that written communication is rife with misunderstandings. And I think I may often look very rude while... well at least I don't mean it :-)
Also since this package soaks up so much of my research time, the frustration of not working on the other projects I like is real. 
So I'm naturally a bit tetchy when it comes to requests, but you're of course no one but me is responsible of my poor career choices :-)
So, please accept my apologies for misinterpreting your comments.

And really, big thanks for the *cmidrule* suggestion, I think it's a very nice addition.
