### ISSUE TITLE
`csw0()` switches levels of logical variable around

### ISSUE THREAD

**Issue by turbanisch** [lrberge/fixest#174]
This is very minor and may well be user error: In an interaction with a logical variable, R normally seems to display the `TRUE` level and drop the other one due to collinearity. If I wrap the interaction in `csw0`, however, R displays the `FALSE` level instead: `disp:vsFALSE`. I have included an example below. 

Is there a way to work around this issue (or is it a feature rather than an issue in the first place)?

``` r
library(tidyverse)
library(fixest)

# create dataset
dat <- mtcars %>% 
  as_tibble() %>% 
  mutate(vs = as.logical(vs))

# without csw: disp:vsTRUE is displayed
feols(mpg ~ disp + vs + disp:vs, data = dat) %>% summary
#> OLS estimation, Dep. Var.: mpg
#> Observations: 32 
#> Standard-errors: Standard 
#>              Estimate Std. Error t value  Pr(>|t|))    
#> (Intercept) 25.638000   2.187000 11.7230 2.5800e-12 ***
#> disp        -0.029370   0.006746 -4.3537 1.6200e-04 ***
#> vsTRUE       8.397700   3.014900  2.7854 9.4830e-03 ** 
#> disp:vsTRUE -0.042186   0.015971 -2.6414 1.3354e-02 *  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 2.7778   Adj. R2: 0.757232

# with csw: disp:vsFALSE is displayed
feols(mpg ~ disp + vs + csw0(disp:vs), data = dat) %>% summary
#> The variable 'disp:vsTRUE' has been removed because of collinearity (see $collin.var).
#> Standard-errors: Standard 
#> Expl. vars.: disp + vs
#>              Estimate Std. Error   t value   Pr(>|t|))    
#> (Intercept) 27.949000   2.201200 12.697000 2.27000e-13 ***
#> disp        -0.036896   0.006715 -5.494400 6.43000e-06 ***
#> vsTRUE       1.495000   1.651300  0.905355 3.72738e-01    
#> ---
#> Expl. vars.: disp + vs + disp:vs
#>               Estimate Std. Error t value  Pr(>|t|))    
#> (Intercept)  25.638000   2.187000 11.7230 2.5800e-12 ***
#> disp         -0.071556   0.014476 -4.9429 3.2000e-05 ***
#> vsTRUE        8.397700   3.014900  2.7854 9.4830e-03 ** 
#> disp:vsFALSE  0.042186   0.015971  2.6414 1.3354e-02 *
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lrberge** [comment]
Hi, this is not really a bug (but definitely not a feature :-)), although it can look weird.

The cause is that each variable that is added in a stepwise fashion is evaluated separately from the variables fixed across models.
This leads, in the case of `csw0(disp:vs)`, to include `disp:vs` *alone* which will consider both values of `vs`. This is not evaluated as the third element of in `disp + vs + disp:vs` which would consider only one value of `vs` because of the presence of `disp`.
Let's illustrate the difference:
```R
# Separate evaluation
coef(lm(mpg ~ vs:disp, data = dat))
#>  (Intercept) vsFALSE:disp  vsTRUE:disp 
#>  30.05646567  -0.04228290  -0.04591104

# Full evaluation
coef(lm(mpg ~ disp + vs + vs:disp, data = dat))
#> (Intercept)        disp      vsTRUE disp:vsTRUE 
#> 25.63755459 -0.02936965  8.39770888 -0.04218648 
```

So in the end there is no switch of the references, there is inclusion of all the factor values and one is removed from collinearity. But indeed, this is not what one should expect.
One solution is then to tell which value to remove explicitly, this can be done with `i()` for instance:
```R
# Solution, explicitly give the ref, using i
feols(mpg ~ disp + vs + csw0(i(vs, disp, FALSE)), data = dat) %>% summary
#> Standard-errors: Standard
#> Expl. vars.: disp + vs
#>              Estimate Std. Error   t value   Pr(>|t|))
#> (Intercept) 27.949000   2.201200 12.697000 2.27000e-13 ***
#> disp        -0.036896   0.006715 -5.494400 6.43000e-06 ***
#> vsTRUE       1.495000   1.651300  0.905355 3.72738e-01
#> ---
#> Expl. vars.: disp + vs + i(vs, disp, FALSE)
#>                Estimate Std. Error t value  Pr(>|t|))
#> (Intercept)   25.638000   2.187000 11.7230 2.5800e-12 ***
#> disp          -0.029370   0.006746 -4.3537 1.6200e-04 ***
#> vsTRUE         8.397700   3.014900  2.7854 9.4830e-03 **
#> vs::TRUE:disp -0.042186   0.015971 -2.6414 1.3354e-02 *
```

Another solution is to include `disp` in the stepwise evaluation (since it is its absence which causes the issue):
```R
feols(mpg ~ vs + sw(disp, disp + vs:disp), data = dat) %>% summary
#> Standard-errors: Standard 
#> Expl. vars.: vs + disp
#>              Estimate Std. Error   t value   Pr(>|t|))    
#> (Intercept) 27.949000   2.201200 12.697000 2.27000e-13 ***
#> vsTRUE       1.495000   1.651300  0.905355 3.72738e-01    
#> disp        -0.036896   0.006715 -5.494400 6.43000e-06 ***
#> ---
#> Expl. vars.: vs + disp + vs:disp
#>              Estimate Std. Error t value  Pr(>|t|))    
#> (Intercept) 25.638000   2.187000 11.7230 2.5800e-12 ***
#> vsTRUE       8.397700   3.014900  2.7854 9.4830e-03 ** 
#> disp        -0.029370   0.006746 -4.3537 1.6200e-04 ***
#> disp:vsTRUE -0.042186   0.015971 -2.6414 1.3354e-02 * 
```

Unfortunately, this problem is a bit too niche for me to implement a solution, especially that it entails a complete modification of how I should evaluate the stepwise variables. But I hope the proposed solutions are not too inconvenient!

And thanks for the reproducible example! :-)

**Comment by turbanisch** [comment]
Thank you so much for looking into it nevertheless! I think both solutions are not inconvenient at all - probably it is good practice to think about explicitly setting the reference level for categorical variables anyways :)
