### ISSUE TITLE
Feature Request: Save FE values to data

### ISSUE THREAD

**Issue by cseveren** [lrberge/fixest#175]
It would be useful to be able to save FE values into the data itself (something like using `fixef` to extract the FEs then `merge` them to the appropriate rows in the originating dataset). This issue was posted before #144, but a comment said that the "use case is fairly limited" and the issue closed. I would counter that saving and working with the fixed effects is actually a relatively common activity (e.g., they often have meaning in trade models, and being able to save FEs is important for doing decompositions). 

I frequently use `reghdfe`'s post-estimation commands in Stata, and it would useful to be able replicate that workflow in `fixest` in R.

As always, thanks for this excellent, high quality, and extremely useful package! It continues to be a great public good.

**Comment by lrberge** [comment]
Hi, I've implemented it in `predict`. Now there's this new argument `fixef` that, if `TRUE`, will return a data frame of size n_obs x n_FE with the fixed-effects coefficients for each row the same number of columns as FEs. If you want the FEs for the original data set, you need to add the argument `sample = "original"` (otherwise it's the estimation sample that is used).

There's an example in `predict`'s help that may be of interest.

My issue with the FEs is that although they can have a meaning, in practice they (very often but not always) can hardly be interpreted because of multiple component problems. But that's another story ;-)

I hope the new feature suits your needs and thanks for the words!

**Comment by cseveren** [comment]
Mega-like. Thanks @lrberge!
