### ISSUE TITLE
Use instrumental variable with fepois()

### ISSUE THREAD

**Issue by etiennebacher** [lrberge/fixest#176]
Hello, thanks for this package! Although I haven't used it a lot so far, it seems very efficient and full of nice functionalities.

I would like to regress bilateral migration flows on various explanatory variables, and therefore I would like to use the Poisson Pseudo Maximum Likelihood (PPML), that is common in the literature. In Stata, I would use `ppmlhdfe`. If I am correct, here I have to use `fepois`, which is the function you compared to `ppmlhdfe` in the benchmark. First of all, is this correct?

I suspect that one of my explanatory variable is endogenous, and therefore I would like to instrument it. However, it is not possible to do with `fepois`:
```
Error in fepois(flow ~ csw0(gdp_ppp, pop, dist, comlang_off, colony, diasp_2001) |  : 
  The argument 'fml' cannot contain more than two parts separated by a pipe ('|'). IVs are available only for 'feols'.
The syntax is: DEP VAR ~ EXPL VARS | FIXED EFFECTS. (No IVs allowed.)
```
I guess this should be possible, if I rely on what [Santos Silva & Tenreyro (2006)](https://direct.mit.edu/rest/article/88/4/641/57668/The-Log-of-Gravity) said in the paper where they recommended the use of PPML (p.646, footnote 16):

> It is worth noting that the PPML estimator can be easily adapted to deal with endogenous regressors (Windmeijer & Santos Silva, 1997) and panel data (Wooldridge, 1999).

How can I both estimate a PPML model and instrument my endogenous variable with `fepois`?

Note that I am not sure whether it is possible to do so with `ppmlhdfe`.

**Comment by lrberge** [comment]
Hi! 

For the first question: yes, you are correct `fepois == ppmlhdfe`.

Regarding IV-Poisson, well, it can be done with first stage OLS, but it's simply not currently implemented.

The big problem is that, to the best of my knowledge (and I'm not an econometrician so said knowledge is fairly limited), there is no theoretically valid analytical covariance for non-linear IV models. This means that the VCOV has to rely on bootstrapping. And since bootstrapping isn't yet implemented in the package, IV-glm will wait until then. 

However, given the recurrence of this question, I'll give a hacky way to get the IV-Poisson estimates:

```R
# Function to get the estimates
ivpois_est = function(fml, data){
    # 1st + 2nd stage OLS
    est_ols = feols(fml, data)
    
    # Getting the residuals
    resid_1st_stage = resid(summary(est_ols, stage = 1))

    # 2nd stage poisson, we add the 1st stage residuals as regressors
    y = model.matrix(est_ols, type = "lhs")
    RHS = model.matrix(est_ols, type = c("iv.endo", "iv.exo"))
    RHS_control_fun = cbind(RHS, resid_1st_stage)

    # FEs, if there // note that vars with varying slopes won't work
    FE = if(!is.null(est_ols$fixef_vars)) model.matrix(est_ols, type = "fixef") else NULL

    # 2nd stage
    feglm.fit(y, RHS_control_fun, FE, family = "poisson")
}

# Function to get the VCOV
ivpois_vcov = function(fml, data, nrep){
    # This is just to give an example, there are many BS schemes possible

    n = nrow(data)
    all_coef = vector("list", nrep)

    for(i in 1:nrep){
        all_coef[[i]] = coef(ivpois_est(fml, data[sample(n, n/2), ]))
    }

    all_coef_mat = do.call("rbind", all_coef)

    var(all_coef_mat)
}

# Function to get both the VCOV and the estimates
ivpois = function(fml, data, nrep = 200){

    res = ivpois_est(fml, data)

    vcov = ivpois_vcov(fml, data, nrep)

    summary(res, .vcov = vcov)
}

# Example
base = iris
names(base) = c("y", "x1", "endo", "inst", "fe")

est_noIV = fepois(y ~ endo + x1 | fe, base)
est_IV = ivpois(y ~ x1 | fe | endo ~ inst, base)
est_IV_noboot = ivpois_est(y ~ x1 | fe | endo ~ inst, base)

etable(est_noIV, est_IV, est_IV_noboot)
#>                           est_noIV             est_IV     est_IV_noboot
#> Dependent Var.:                  y                  y                 y
#>                                                                        
#> endo            0.1221*** (0.0150)   0.0701. (0.0409) 0.0701** (0.0272)
#> x1                0.0778* (0.0339) 0.1033*** (0.0251) 0.1033** (0.0314)
#> resid_1st_stage                       0.0599 (0.0406) 0.0599** (0.0222)
#> Fixed-Effects:  ------------------ ------------------ -----------------
#> fe                             Yes                Yes               Yes
#> _______________ __________________ __________________ _________________
#> S.E. type                   by: fe             Custom            by: fe
#> Observations                   150                150               150
#> Squared Cor.               0.86314            0.86715           0.86715
#> Pseudo R2                  0.02676            0.02687           0.02687
#> BIC                         570.76             575.71            575.71
```


In the previous code chunk are three functions: the first to get the estimates, the second to get the VCOV via bootstrapping and finally the last one which calls the two previously defined functions to obtain both the estimates and the VCOV.

I must say that this solution is excruciatingly slow. The use case of the package is "one estimation on a very large data set with many *many* fixed-effects" and **not** "multiple small estimations". This means that the user-level functions (`feols`, `fepois`, etc) suck at bootstrapping because of the overheads they incur (typically a few ms due to numerous user-friendly consistency checks + non-standard evaluations). This said, of course as the data sets grow in size, the overheads become less and less problematic runtime-wise.
Furthermore this solution computes a lot of stuff that's not needed and which can be redundant, and finally it does not take advantage of some numerical tricks to hasten bootsrapping (like QR updating). 
But it works: for any number of endogenous regressors, with/without fixed-effects.

Of course you have to adapt many things but I think it can be used as a good starting point.

I hope you'll enjoy the package and that the previous code will help!

**Comment by etiennebacher** [comment]
Thanks a lot for the detailed answer and the workaround! Just in case someone else wants to use it, the code above doesn't work with multiple regressions, i.e when using `csw()`, `sw()`, etc, in the formula. This can probably be adapted though.

**Comment by etiennebacher** [comment]
I have a question about the output of your custom IV poisson functions. Why is there `resid_1st_stage` in the regressors for the second step for IV poisson but not in the regressors for "basic" IV? 
```
base = iris
names(base) = c("y", "x1", "endo", "inst", "fe")

# Basic IV
est_iv = feols(y ~ x1 | fe | endo ~ inst, base)
est_iv
etable(est_iv)

#                            est_iv
# Dependent Var.:                 y
# 
# endo            0.4487** (0.0288)
# x1               0.5887* (0.0600)
# Fixed-Effects:  -----------------
# fe                            Yes
# _______________ _________________
# S.E.: Clustered            by: fe
# Observations                  150
# R2                        0.83890
# Within R2                 0.57748

# Poisson IV
est_iv_pois = ivpois(y ~ x1 | fe | endo ~ inst, base)
est_iv_pois
etable(est_iv_pois)

#                        est_iv_pois
# Dependent Var.:                  y
# 
# endo              0.0701. (0.0411)
# x1              0.1033*** (0.0246)
# resid_1st_stage    0.0599 (0.0409)
# Fixed-Effects:  ------------------
# fe                             Yes
# _______________ __________________
# S.E. type                   Custom
# Observations                   150
# Squared Cor.               0.86715
# Pseudo R2                  0.02687
# BIC                         575.71
```
Is `resid_1st_stage` a result I should care about? Sorry if this is a really basic question, I am just surprised it appears only with Poisson IV.

**Comment by leucotheas** [comment]
@lrberge @etiennebacher I just wanted to clarify, in the previous document that I mentioned ([http://econ.msu.edu/faculty/wooldridge/docs/qmle_endog_r3.pdf](http://econ.msu.edu/faculty/wooldridge/docs/qmle_endog_r3.pdf) ) it is actually equation 4.17 that corresponds to Poisson estimation, which if I understand well is what @lrberge is doing in the code suggested
