### ISSUE TITLE
Faster spatial HAC calculation?

### ISSUE THREAD

**Issue by karldw** [lrberge/fixest#178]
Thank you @lrberge and @kylebutts for bringing spatial HAC to fixest! (Ref #177, #114)

One quick thought: it should be possible to make the calculation faster using trees. All of the Conley examples I've seen use a double for-loop to check distances between points, which means you have to check roughly _n_<sup>2</sup> / 2 distances if you have _n_ points. [`cpp_vcov_conley`](https://github.com/lrberge/fixest/blob/9ac6042659da236dac002eeb0ba18182fa789355/src/vcov_related.cpp#L601-L636) has clever shortcuts to reduce computation time, but I think it's still O(_n_<sup>2</sup>). 
An alternative to the double for-loop is to build a tree, then for each point, query the tree for nearby points. I think that approach is only O(_n_ log _n_), so could be faster for very big datasets. (I took a [stab at this tree-based calculation](https://github.com/karldw/conleySE/blob/4fb680106896786a6068b7f347f98ce97a08197e/core.py#L317) a while ago in python, but ended up dropping the project.)

It looks like the [_rtree_](https://github.com/hunzikp/rtree) package (which wraps the Boost geometry library) offers a useful tree structure and will be on CRAN soon. [_BH_](https://cran.r-project.org/web/packages/BH/) also includes the geometry library. Either of these would be pretty heavy dependencies to add just to speed up one type of vcov calculation.

I wanted to make sure faster data structures were on your radar, but feel free to close this issue!

**Comment by lrberge** [comment]
Hey! Thanks for pointing to the r-tree algorithm, I didn't know about it!

Just to clarify a few points:
 - The algorithm is **not** *O*(n<sup>2</sup>), with n the number of observations, it is *O*(n<sub>L</sub><sup>2</sup>) with n<sub>L</sub> the number of locations. That makes quite a difference especially that in panel data when n grows n<sub>L</sub> needs not to grow. 
Further if you pixelize the data, it becomes *O*(n<sub>PL</sub><sup>2</sup>) with n<sub>PL</sub> the number of pixelized locations. That can be useful because even when using micro data and the number of units grow, n<sub>LP</sub> very likely won't so much.

 - The algorithm cannot be less than *O*(n<sup>2</sup>), even with the best algorithms. Indeed, even if we visit only the points that need to be visited, we still need to make the sum across **all** pairs of points whose distance is lower than a cutoff. And there are roughly _a_*n<sup>2</sup> such pairs with *a* a factor depending on the cutoff. Example: assuming points are randomly allocated on a rectangle of surface S, each point has roughly S/cutoff<sup>2</sup> neighbors, leading to a *O*(n<sup>2</sup>cutoff<sup>2</sup>/S) complexity, hence *O*(n<sup>2</sup>). 

The algorithm I implemented is optimal when data is scattered vertically but slow when data is scattered horizontally. I initially wanted to implement a blockwise algorithm (in hindsight close to the r-tree idea) but I found the non flat aspect of the earth to be too much of a pain in the neck especially that... welll... I have no use of Conley SEs. But I may give it another go then ;-) I'll let you know!

**Comment by karldw** [comment]
Ah, thank you. Clearly you've thought about this much more deeply than I have!

Two quick thoughts: 

>The algorithm cannot be less than _O_(n<sup>2</sup>)

I was thinking about the wrong kind of asymptotics – imagining n<sub>L</sub> increasing by expanding the land area, but keeping a fixed density of locations. Your example, with increasing _density_ of locations, is the relevant version in almost every case.

> But I may give it another go then

This is a fun algorithm discussion, but what you've done already is superb!

**Comment by lrberge** [comment]
@karldw: thanks! devising algorithms is indeed (too much?) fun, and no doubt is the main reason I spend so much time on this kind of things!

@kylebutts: actually I'm not complaining about computing the distance between two points, I'm complaining that the globe *cannot* be mapped to a rectangle, which is a preamble to the fast algorithm I have in mind. But I have found some workarounds, we'll see!
