### ISSUE TITLE
Bootstrap standard errors

### ISSUE THREAD

**Issue by Fab993** [lrberge/fixest#18]
Hi, 

First of all, thanks a lot for your incredibly useful package. I have a minor issue with it that I would like to report. Any help is much appreciated.

I am using the function feglm and I need bootstrap standard errors (BSE). I have programmed up the bootstrap routine myself. My problem is that I don't manage to display the BSE with etable(). Below my code:

`n.Boot <- 1000`
`frm      <- y ~ x  |  i + j`
`out      <- feglm(frm, data = df, notes = FALSE)`
`B.se    <- Run_bootstrap(n.Boot,frm)  # My bootstrap routine`

where `df` contains my data. I have then tried to substitute my own BSE with those provided by feglm as follows:

`out[["se"]] <- B.se`
`out[["coeftable"]][["Std. Error"]] <- B.se`

and then do

`etable(out)`

However, this is not producing the desired result. I would like to ask you if there is any way to address my point (maybe another function for displaying results besides etable or stargazer?)

I thank you in advance for your help. 

Below my system and package info:

> package: fixest   0.4.0      2020-03-29 [1] CRAN (R 3.6.3)
> version:  R version 3.6.3 (2020-02-29)
> os :      Windows 10 x64 
> system:   x86_64, mingw32   
> ui :      RStudio

**Comment by lrberge** [comment]
Hi, first thanks for using it, I'm glad you find it useful!

Yes, it's a quirk from the package (actually it allows the user to perform a summary with the same parameters to all the models, without forcing summary when not necessary [bottom line: it's useful although technical]). 
Only the "coeftable" from summary objects are untouched, otherwise, summary is re-performed and `etable` will show the results from the new coeftable.

Notice that you'll also have to provide the p-value manually since the one from the coeftable is used. 

Notice the behavior below (only one of the two is modified):

```r
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

res = feols(y ~ x1, base)

res_bis = summary(res)

res$coeftable[, 2] = 5
res_bis$coeftable[, 2] = 5

etable(res, res_bis)

#                                  res      res_bis
#(Intercept)         6.526*** (0.4773) 6.526*** (5)
#x1                   -0.2234 (0.1546)  -0.2234 (5)
#___________________ _________________ ____________
#Observations                      150          150
#S.E. type: Standard          Standard     Standard
#R2                            0.01382      0.01382
#Adjusted R2                   0.00716      0.00716
```

That's not the best way to provide custom SEs, but it works. I'll try to implement something easier in the future.

**Comment by Fab993** [comment]
Hello,

thanks for your reply. That's already very useful. You can close this issue if you want.

**Comment by lrberge** [comment]
Perfect then, thanks!

**Comment by lrberge** [comment]
Hi, just to mention that I'll release the version 0.6.0 at the end of the month and it will be possible to provide a custom VCOV matrix to summary (new argument `.vcov`). It'll make this task much easier! :-)

**Comment by Fab993** [comment]
great news, will make your library even more useful. Won't miss the update. Thanks a lot.
