### ISSUE TITLE
predict.fixest() on regressions with lagged variables

### ISSUE THREAD

**Issue by nreigl** [lrberge/fixest#191]
The predict.fixest() function seems to fail on regressions with lagged variables when trying to calculate the effects for a certain term. The error occurs when the panel is set up on-the-fly using  the argument `panel.id` and when the panel data set is constructed using  the function `panel`.  

First, using the `predict.fixest()` on a regression containing only the contemporaneous value of the variable *x1*. 

```R
library(fixest)
library(ggeffects)
data(base_did)
est1 <- feols(y ~ x1, base_did)
x1base_did <- new_data(est1, terms = "x1")
predict(est1, type = "response", newdata = x1base_did)
#> [1] -12.757901  -7.842350  -2.926798   1.988753   6.904304  11.819855
```

Use *x1* and the first lag of *x1* in the regression. 

```R
# setting up the panel
pdat = panel(base_did, ~id + period)
# Estimate regression using the contemporaneous value of x1 and the first lag of x1
est2 = feols(y ~ l(x1, 0:1), pdat)
summary(est2)
#> OLS estimation, Dep. Var.: y
#> Observations: 972 
#> Standard-errors: Standard 
#>            Estimate Std. Error   t value Pr(>|t|))    
#> (Intercept) 2.234800   0.157744 14.167000 < 2.2e-16 ***
#> x1          0.994800   0.053151 18.716000 < 2.2e-16 ***
#> l(x1, 1)    0.040962   0.054006  0.758473  0.448353    
#>  ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 4.9092   Adj. R2: 0.264064
x1base_did <- new_data(est2, terms = "x1")
predict(est2, type = "response", newdata = x1base_did)
#> Error: in predict.fixest(est2, x1base_did):
#> In the argument 'panel.id', the variables 'id' and 'period' are not in the data set.
```

I might miss here something using the function `new_data()` from the ggeffects package. In principle I just want to predict the effects of a single contemporaneous term from a regression containing lagged predictors.  My goto approach would be something like this: 

```R
ggpredict(est1, c("x1"))
#> x1 | Predicted |           95% CI
#> ----------------------------------
#> -15 |    -12.76 | [-14.26, -11.25]
#> -10 |     -7.84 | [ -8.87,  -6.81]
#>  -5 |     -2.93 | [ -3.50,  -2.35]
#>    0 |      1.99 | [  1.70,   2.28]
#>    5 |      6.90 | [  6.34,   7.47]
#>   10 |     11.82 | [ 10.80,  12.84]
ggpredict(est2, c("x1"))
#> Error: in predict.fixest(model, newdata = fitfram, type = p...:
#> In the argument 'panel.id', the variables 'id' and 'period' are not in the data set
```

**Comment by lrberge** [comment]
Hi, hmmm this is in fact a very complex problem. 

I don't think applying `ggpredict` with lagged variables created on the fly can work. As said in the error message, to create lagged variables, one needs panel identifiers. Without them the lagged variable cannot be created and hence `ggpredict`/`predict` can't work (and the "typical values" of panel identifiers make no sense so can't really be used).

To make it work, it would require `ggpredict` to have a routine specific to a `fixest` object with lagged variables **and** that I amend the `predict` function to cope with lagged data that does not require to be recreated. So it requires quite a bit of coordination. That's a problem much more complex that what it looks at first sight.

The workaround solution would be to create all the lagged variables ex ante and then run the model with these variables. But that's really inconvenient I know. 
By the way, for information, I've added the new operator [`.[]`](https://lrberge.github.io/fixest/reference/xpd.html#dot-square-bracket-operator-in-formulas) that can be used in formulas to quickly include many variables at once.

```R
data(base_did)
base = base_did
base$x1.L1 = lag(x1 ~ id + period, 1, base)
base$x1.L2 = lag(x1 ~ id + period, 2, base)

# with regex: all x1 variables
a = feols(y ~ ..("x1"), base)
#> NOTE: 216 observations removed because of NA values (RHS: 216).

# with .[], maybe more explicit
b = feols(y ~ x1 + x1.L.[1:2], base)
#> NOTE: 216 observations removed because of NA values (RHS: 216).

etable(a, b)
#>                                  a                  b
#> Dependent Var.:                  y                  y
#>                                                      
#> (Intercept)      2.464*** (0.1697)  2.464*** (0.1697)
#> x1              0.9940*** (0.0579) 0.9940*** (0.0579)
#> x1.L1              0.0081 (0.0584)    0.0081 (0.0584)
#> x1.L2              0.0157 (0.0585)    0.0157 (0.0585)
#> _______________ __________________ __________________
#> S.E. type                      IID                IID
#> Observations                   864                864
#> R2                         0.25697            0.25697
#> Adj. R2                    0.25438            0.25438
```

I'm closing because I can't do much, sorry. But I hope you find a way!
