### ISSUE TITLE
Feature request: broom methods for fixest models

### ISSUE THREAD

**Issue by karldw** [lrberge/fixest#2]
Thanks for the great package!

It would be convenient (for me, hopefully for others) if fixest had `tidy.fixest`, `glance.fixest`, and `augment.fixest` methods.  The broom docs provide recommendations for adding these methods: https://broom.tidyverse.org/articles/adding-tidiers.html

``` r

library(broom)
library(fixest)

tidy(lm(mpg ~ wt, data=mtcars))
#> # A tibble: 2 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)    37.3      1.88      19.9  8.24e-19
#> 2 wt             -5.34     0.559     -9.56 1.29e-10
tidy(feols(mpg ~ wt, data=mtcars))
#> Error: No tidy method for objects of class fixest
```

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What do you think? 
If anyone else wants to tackle this, please feel free. If not, I can submit a PR sometime in the next few weeks.

**Comment by lrberge** [comment]
Thanks for your suggestion!

Actually I think the natural location of this implementation would be in the _broom_ package rather than in *fixest*. The main reason is that I don't use _tidyverse_ at all (and I'm not a _tibble_ fan) and would like to keep the package as free as possible from imports and dependencies. 

Yet for _tidyverse_ users, your suggestion is of value and a very good idea. Would it be possible for you to write a PR for the _broom_ package instead? Of course, I can help in the process if there are any requests in the objects returned by _fixest_.

**Comment by karldw** [comment]
Sounds good! I'll open an issue there.

**Comment by karldw** [comment]
@lrberge, it's not at all urgent, but would you consider another CRAN release in the next few months? The broom methods I wrote depend on some of the more recent changes (e.g. NA behavior in #3), and it would be nice to get them out into the world.

**Comment by lrberge** [comment]
You've done it, that's great! Thanks a lot!
Indeed, I'm planning to release a new version by the end of the month. Thanks again!

**Comment by lrberge** [comment]
Just to mention: I've just submitted to CRAN, it should be out soon!

**Comment by karldw** [comment]
Wonderful, thank you!
