### ISSUE TITLE
Reference levels of irregular fixed effects

### ISSUE THREAD

**Issue by jurojas5** [lrberge/fixest#214]
Hi!

Thank you once again for your efficient package. I have been using it for over a year now.

I am trying to estimate a structural gravity model with international and intra-national trade and three types of fixed effects: exporter-year, importer-year and symmetric exporter-importer (exporter-importer = importer-exporter). Is there any way to select the levels omitted (set to "0") in the calculation of fixed effects when they are not regular (more than one reference level)?

**Comment by lrberge** [comment]
Hi! Nice to see a long time user :-). 

No, it cannot be done within the package. The main problem is that there is no general answer to this problem. 
But in your case, because of the high regularity of the data, it can be done. Typically, there are > 1 references because (I guess) some groups of countries are separated: some never interact with the others (or at least the interactions are not in the data set).
You could find the groups by finding the components of the network where countries are the nodes and exporter-importer presence in the data set is the link. Then you just have to pick one reference for each component.

To give an idea of what's going on: imagine a data set with four countries FR-DE-CA-US and importer FEs, exporter FEs. 
The full data set is like:
```
Im Ex trade
FR FR $
FR DE $
DE DE $
DE FR $
US US $
US CA $
CA CA $
CA US $
```


Here you can clearly see that the data set is partitioned by continent. If you take France-importer as a reference, then you can retrieve the FE values for DE-importer, FR- and DE-exporter. **But you cannot identify the effect of any FE related to CA or US!** Indeed, there still exists an infinity of solutions for the 4 fixed-effects relating to CA and US, so you need to fix one of the 4.
That's the idea.


Note that, in the trade context, this is just a missing data story. If you had just one more line, everything would be fine:
```
Im Ex trade
FR FR $
FR DE $
DE DE $
DE FR $
US US $
US CA $
CA CA $
CA US $
FR US $ <-- New information
```

This simple additional line changes everything since it connects the two partitions that would otherwise have been separated. Now by fixing only one value, all the others follow.

Typically when you have just 2 FEs, you just need to find the components and set one reference per component. When you have 3+FEs you cannot rely on components any more and it becomes super tricky: there's no real way to find out.

But thanks to the very balanced structure of your data, your 3-way FE can be boiled down to a 2-way problem as I mentioned (it's very specific to your case though). 

I hope the problem is clarified and that you'll be able to find a solution!
