### ISSUE TITLE
fepois offset stopped working

### ISSUE THREAD

**Issue by gbekes** [lrberge/fixest#223]
Hi

I updated fixest 0.9.0 to 0.10.1 (CRAN) running R 4.0.5. The offset option in fepois stopped working. 

My model is on a y=count of actions, x=bilateral similarity dummy. 
Data is three-way panel, with with from (`id1`) to (`id2`) in a `year`.
It's `fepois()`, but with with **exposure** modelled as `offset = ln minutes agents shared together`. 

```
model1 ="action_count ~  bilateral_dummy"
fe2=   "| id1^year+ id2^year "

pois1fe=fepois(formula(paste0(model1, fe2)) ,   
               offset(~ln_minutes_shared)     , data=data  )
```
After the update, offset stopped working, it's simply omitted. 

After some trials, and checking the change log, I tried this quick random fix and seems to work (I use etable anyway re SE)

```
pois1fe=fepois(formula(paste0(model1, fe2)) ,   
               offset(~ln_minutes_shared)  , vcov = "hetero"   , data=data  )
```

Thanks so much!

Gabor

**Comment by lrberge** [comment]
Hi Gabor!

Two comments.

1) It's not a bug: in version 0.10.0 I've inserted the (new) `vcov` argument right after the `data` argument, pushing away `offset` by one slot. I've done so since `vcov` is more used than `offset`. But I didn't announce the change in the package startup message: my bad! I've fixed it.
To make it short: you now need to use the argument name explicitly. Just change `offset(~ln_minutes_shared)` into `offset = ~ln_minutes_shared`  and it will work. 

2) You can use macro variables or the new dot square bracket operator to handle formulas. It may be more convenient/clearer than pasting and converting to a formula.

```r
# With formula macros
setFixest_fml(..lhs = "action_count", ..rhs = "bilateral_dummy", 
              ..fe = "id1^year+ id2^year")


fepois(..lhs ~ ..rhs | ..fe, etc)
# Leads to: action_count ~ bilateral_dummy | id1^year + id2^year


# With DSB
lhs = "action_count"
rhs = "bilateral_dummy"
fe = c("id1^year", "id2^year")
# Note that fe = "id1^year+ id2^year" would also work

fepois(.[lhs] ~ .[rhs] | .[fe], etc)
# Also leads to: action_count ~ bilateral_dummy | id1^year + id2^year
```
Hope this helps!

**Comment by gbekes** [comment]
Works like a charm! :-) Thanks Laurent.
