### ISSUE TITLE
A minor bug related to etable?

### ISSUE THREAD

**Issue by pei-huang** [lrberge/fixest#228]
Hi Laurent,

There seems to be a minor bug in ```etable``` when outputting Latex tables with ```tablefoot = FALSE```, where a bottom line or two bottom lines are missing. Below is some reproducing code:

```
library(fixest)
data(airquality)

# Setting a dictionary 
setFixest_dict(c(Ozone = "Ozone (ppb)", Solar.R = "Solar Radiation (Langleys)",
                 Wind = "Wind Speed (mph)", Temp = "Temperature"))

est = feols(Ozone ~ Solar.R + sw0(Wind + Temp) | csw(Month, Day), 
            airquality, cluster = ~Day)

etable(est, tex = TRUE, drop.section = c("fixef", "slopes", "stats"), 
       style.tex = style.tex(tablefoot = FALSE))
```

However, when setting ```main = "aer"``` in ```style.tex```, a bottom line seems to exist. Maybe that's the style you set up?

May I also ask if the ```fixest``` has a built-in function to make a table with multiple panels, which share the same column headers? One example is that we may want to make a table with two panels: one panel with OLS estimations and the other panel with IV estimations.

**Comment by lrberge** [comment]
Hi Pei,

It's not really a bug, it's a legacy of a bad design choice. 
I'm pushing to release v1.0 (hopefully before the end of the year) and I'm improving quite substantially the Latex exports. In so doing I rationalised this, now top/bottom line can be equal to `simple` or `double` and the bottom line is now showing at the "expected" location, irrespective of the footer within the table. 

On the panels: that's in the pipelines for a while now but it's a bit complex to implement robustly, so that will have to wait! But it will be there at some point.

**Comment by pei-huang** [comment]
Thank you for clarifying this!
