### ISSUE TITLE
 coef.just="." and tex=TRUE

### ISSUE THREAD

**Issue by mjdcurtis** [lrberge/fixest#245]
I know the documentation for coef.just says DF only, but this is possible for tex=TRUE if using \phantom.

e.g. change:

`0.05$^{***}$`

to:

`\\phantom{$^{***}$}0.05$^{***}$`

**Comment by lrberge** [comment]
Everything is possible. But your "solution" is so far from having any use...

1. it does not work for non mono fonts
2. since the columns are centred, adjustments have to be made on both sides -- or columns should be left aligned, while non numbers should be centred, which requires tedious extra bookkeeping
3. significance signs are tricky to handle and any kind of sign can be user-provided (e.g. what's the width of \\dagger?)
4. you need to take care of user-provided coefficient formatting (like \*\*5.32$^{***}$\*\*) which takes 0 space on end-text but takes code length
5. the internal code has to be completely reformatted to put number columns together (not just coefficients, but also statistics and user-provided rows) since the formatting has to be applied only once we know all the numbers of the column. Such reformatting was so far never needed and would increase code complexity and reduce maintainability.

On top of that, *I don't care about that feature*. So since you seem to care and to have the solution, please feel free to write a PR that handles all the previous cases I've just mentioned.

Next time, please do just *request* the feature. And avoid jotting down something like you have the solution and I have to thank you for it, while in fact you didn't think about the problem for more than 10s and have no idea what it entails.

-----

I'm sorry for the tone but that really pisses me off. This feeling of entitlement is really beyond what I can support. 

So let's do something: put yourself in my shoes and assume I'm implementing the feature. Really do write the code that handles all the previous cases I've mentioned (I mean really all the cases, because I don't implement solutions that are not general), and keep track of the time it takes. Once you're done (if you're done at some point), ask yourself if it's really reasonable to demand that I implement that feature for free only to suit you. Would you give all that (precious little) research time away for something you wouldn't use yourself? Let me doubt it.

**Comment by mjdcurtis** [comment]
I must have made an etiquette mistake, sorry I am new to github and thought I was making a feature request. I certainly did not wish to upset you and thanks for providing the great package!

For the little it is worth, `\phanton{#1} ` will actually display the exact whitespace that `#1` would take if it were actually typeset. It's not hard to use regex to substitute it in to the TeX output before exporting, so I can just keep doing that .

**Comment by lrberge** [comment]
Ah OK, I see. Indeed, that's easy but the coefficients don't end up being dot-aligned, as was the request. It only offsets the impact of the significance signs on the centering, that's something quite different.

**Comment by lrberge** [comment]
Sorry for the ire, it stems from a misunderstanding. I really thought it was about dot alignment (like the title suggested!) which is much more difficult than what it seems and for which `phantom` is not sufficient.

Remember that it's written communication, rife with misunderstandings: so the issues should be as detailed as possible to avoid these. It's a reminder that when I have the time I should also write a "feature request" guideline.

Otherwise, that's a nice suggestion and very easy to implement. I've never thought about it before but I even think there's no objection to it becoming the default behavior. Thanks. I'll let you know.

**Comment by mjdcurtis** [comment]
Sorry to have bothered you! You are right I should have been more detailed, my bad.
