### ISSUE TITLE
Allow interaction with variables wrapped in sw()

### ISSUE THREAD

**Issue by turbanisch** [lrberge/fixest#247]
Sometimes I would like to estimate multiple models by *exchanging* a certain explanatory variable, e.g. an interaction term. Intuitively, I would expect something like this to work: 

```r
fixest::feols(disp ~ drat + drat:sw(cyl, am, vs), 
      data = mtcars)
```

But apparently `sw()` and its relatives cannot be combined that way so the only solution seems to spell out each interaction like so 

```r
fixest::feols(disp ~ drat + sw(drat:cyl, drat:am, drat:vs), 
      data = mtcars)
```

Would it make sense/be feasible to allow `sw()` to work like this? Or is there any other technique to achieve the same result that I am not aware of? Of course I could use base functions to build a list of formulas and then estimate each with `feols()` but I think it would be nice to be able to use the built-in helpers.

```r
fmls <- list(~cyl, ~am, ~vs)
purrr::map(fmls, update, disp ~ drat + .:drat)
```

**Comment by grantmcdermott** [comment]
Agree that direct support for interactions with `sw()` would be useful. 

Mind you, you can emulate this using the [dot-square-bracket](https://lrberge.github.io/fixest/reference/xpd.html#dot-square-bracket-operator-in-formulas) syntax. Note that you need the leading comma after the `[` to indicate comma separate variables.

```r
fixest::feols(disp ~ drat + sw(.[, "drat:.[c('cyl', 'am', 'vs')]"]), 
              data = mtcars) 
```
Or, if you prefer to break things up into two steps and not worry about matching quotation marks:
```r
vars = c("cyl", "am", "vs")
fixest::feols(disp ~ drat + sw(.[, "drat:.[vars]"]), 
              data = mtcars) 
```

**Comment by lrberge** [comment]
Hi everyone! 

Agreed it would be neat if interactions could work out of the box. 
Of course that's possible to implement, but it's not as straightforward as it seems at first sight since it actually involves a lot of non standard parsing, and implementing that properly is time consuming.

Further, the value added of implementing it is low given that workarounds exist (although they aren't as neat), and the use is likely to be marginal.

On the possible solutions, well Grant has said it all already! 

I'd just add one last thing: now (current dev version, which will be the 0.10.2 CRAN version soon, with newish commit) the true [`dsb`](https://lrberge.github.io/fixest/reference/dsb.html) function is applied in nested dot-square-brackets (and not a weak copy). This means that the slash operator works, leading to a syntax a tad more compact for the first example:

```R
xpd(~sw(.[, "drat:.[/cyl, am, vs]"]))
#> ~sw(drat:cyl, drat:am, drat:vs)
```

**Comment by lrberge** [comment]
Btw I've added that item in my package todo list so this feature may get into the package some day!
