### ISSUE TITLE
feols coef table and summary results not consistent? 

### ISSUE THREAD

**Issue by liboliba** [lrberge/fixest#294]
Dear Author, I wonder what is the difference between feols coef table and summary results?

For example: 
> res = feols(Sepal.Length ~ Petal.Length | Species[Sepal.Width], iris)
> res
OLS estimation, Dep. Var.: Sepal.Length
Observations: 150 
Fixed-effects: Species: 3
Varying slopes: Sepal.Width (Species: 3)
Standard-errors: Clustered (Species) 
             Estimate Std. Error t value Pr(>|t|)    
**Petal.Length 0.822045    0.10061  8.1706 0.014651 ***  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.298903     Adj. R2: 0.863326
                 Within R2: 0.518738
> res$coeftable
              Estimate Std. Error  t value     Pr(>|t|)
**Petal.Length 0.8220454 0.06621323 12.41512 1.793101e-24**

As you can see the SE and subsequently the p values are not the same. 

What causes such difference?

Thanks & regards
Libo

**Comment by liboliba** [comment]
I would guess that has something to do with the type of SE estimated and reported:
https://cran.r-project.org/web/packages/fixest/vignettes/standard_errors.html

**Comment by liboliba** [comment]
> 

Yes indeed.
Depending on the design, often there are settings where clustered SE is preferred hence vcov= two way or cluster.

**Comment by lrberge** [comment]
What Grant means is that the `$coeftable` element straight from the fitted model is **always** using IID SEs (unless you passed the argument `vcov`).

This simple fact explains the difference between the SEs of the two sets of coefficients tables, since in the presence of fixed-effects (FE) the default VCOV is clustered according to the first FE. (The computation of the VCOV is delayed at "summary" time [which is implicitly proc'ed when printing] to avoid unnecessary computations if the default VCOV is not the same as the one the user wants.)

In fact, the `$coeftable` slot is not intended for direct use from the user. In general, one should always use the user-level functions that are available when they exist. In this case, just use the function `coeftable()` and you will obtain the same coefficients table as the one that is printed.
