### ISSUE TITLE
Any plan to offer a python package

### ISSUE THREAD

**Issue by yceny** [lrberge/fixest#30]
This is not an issue. But I am wondering do you have any plan to offer a python package for fixest. I feel that most econometric estimation packages are provided in R.

But when it comes to large companies that manage big data analytics, support for python is much greater than that for R. 

Just a thought.

**Comment by lrberge** [comment]
Thanks for the thought. But given that every time I do software development I sacrifice a part of my career in economics by not working on more important projects, the simple answer is no. No python implementation in sight.

What I could do instead it to provide a generic C++ version of the demeaning algorithm which constitutes the workhorse of the package. That code could then be easily implemented in any other language. The cost to do that is quite small (but positive though).

However, my package is fast also because I optimized each and every step of the estimation process (from variable creation, NA removal, etc, etc). You can see that in the benchmarks with only one fixed-effect (where the demeaning algorithm has no leverage). These kind of optimizations are very software specific and thus are not easy to generalize.
