### ISSUE TITLE
etable() on FE-Models without any IVs

### ISSUE THREAD

**Issue by simonschoe** [lrberge/fixest#300]
Hi there,

I am currently concerned with running simple fixed effects models without any true independent variables to decompose the variation in the DV. However, it appears `etable()` does not properly work with models that only include an intercept and fixed effects:

```r 
mod1 <- iris %>% 
  fixest::feols(Petal.Width ~ 1 | Species, data = ., vcov = ~ Species)

mod2 <- iris %>% 
  fixest::feols(Sepal.Width ~ 1 | Species, data = ., vcov = ~ Species)
  
fixest::etable(mod1, mod2, headers = c("Petal", "Sepal"))
```
```
Error in `[.data.frame`(a, , 1) : undefined columns selected
```

I observe a similar behavior when performing stage-wise fixed effects inclusion, it only returns the output for a *single* model:
```r 
iris %>% 
  fixest::feols(Sepal.Width ~ 1 | csw0(Species, Petal.Width),  data = .)
```
```
Standard-errors: IID 
Fixed-effects: 1
            Estimate Std. Error t value  Pr(>|t|)    
(Intercept)  3.05733   0.035588 85.9083 < 2.2e-16 ***
---
Fixed-effects: Species
No variable (only the fixed-effects).
---
Fixed-effects: Species + Petal.Width
No variable (only the fixed-effects).d
```
I am happy for any kind of help! And thanks for the great package! :)

**Comment by lrberge** [comment]
Hi Simon, in fact it turns out that models without any variable to estimate (which actually may sound weird stated that way :-)) never worked on `etable`.
Now it's fixed. While I was at it, I even added a `drop.section = "coef"` if you wish to remove the coefficients section.

Thanks for the reproducible example and the kind words :-)
