### ISSUE TITLE
fixest standard error adjustment

### ISSUE THREAD

**Issue by alanpaulkwan** [lrberge/fixest#31]
Love this package. The performance is an absolute game changer. However I noticed some large differences between lfe and fixest when clustering. Here’s some sample code I wrote generated from a thread examining how lfe was too conservative relative to Stata, which is now 'fixed'. https://github.com/sgaure/lfe/issues/1

I wonder if it's worth aligning the standard errors here.

Here's sample code that replicates the issue
```

# Generate 500 FE levels, with 5 obs each, nested within 50 clusters
n_clusters <- 50
n_obs_per_fe_level <- 5
n_fe_levels <- 500
n_obs <- n_obs_per_fe_level * n_fe_levels
n_fe_per_cluster <- n_fe_levels / n_clusters
n_obs_per_cluster <- n_obs / n_clusters

# Make 500 FE levels
fe <- sort(rep(1:n_fe_levels, length.out = n_obs))
# Make clusters that nest FE levels
cl <- ceiling(fe / n_fe_per_cluster)


draw_one_cluster <- function(N) {
  # Each cluster has its own mean and se for epsilon.
  cluster_eps_mean <- rnorm(1)
  cluster_eps_sd <- 10 * runif(1)
  rnorm(N, mean=cluster_eps_mean, sd = cluster_eps_sd)
}
eps <- unlist(
  replicate(n_clusters, draw_one_cluster(n_obs_per_cluster), simplify = FALSE)
)

x <- rnorm(n_obs, 0, 10)
y <- 0.02 * x + fe / 100 + eps

DF <- data.frame(cl, y, x, fe)

# haven::write_dta(DF, "~/test_data.dta")

mod = lfe::felm(y ~ x | fe | 0 | cl, data=DF)
summary(mod)

mod = fixest::feols(y ~ x | fe , data=DF)
summary(mod,cluster=DF$cl)

```

**Comment by lrberge** [comment]
Hi, thanks for the kind words! :-)

I'm glad I kind of anticipated that question! :-D

As of version 0.6.0, some small bugs were corrected regarding the degrees of freedom calculation and I finally settled on the default standard-errors. Now the SEs are computed in a similar fashion as **reghdfe** for clustered standard-errors (i.e. nesting is taken into account).

You can find all the details on how the SEs are computed in **fixest** in this vignette: [On standard-errors](https://cran.r-project.org/web/packages/fixest/vignettes/standard_errors.html). I also compares the SEs to other software, including **lfe** and **reghdfe**.

The previous example of yours now leads to:
```R
> library(lfe) ; library(fixest)
> 
> mod_felm = felm(y ~ x | fe | 0 | cl, data=DF)
> mod_fixest = feols(y ~ x | fe , data=DF)
> 
> rbind(se(mod_felm), se(mod_fixest, cluster = "cl"))
#>               x
#> [1,] 0.01562965
#> [2,] 0.01562965
```

**Comment by alanpaulkwan** [comment]
Awesome, perhaps my laptop had the old version loaded. I just tried my example after a fresh install and it works, will test on some other regression specifications. Thanks!

**Comment by alanpaulkwan** [comment]
Trying 0.6 on another dataset (not a stylized example), I do find some important differences when running a post*treated context. While the estimates are similar, (1) the within-subject FE does not wipe out a time-invariant treatment indicator (although its almost zero), (2) the standard errors even when restricting it are slightly different still. I can PM an example.

**Comment by lrberge** [comment]
Something looks weird indeed. Please do send me the code/example.

**Comment by lrberge** [comment]
Thanks for sending me the code and data. There are two separate problems.

## On wiping out the collinear variables
This is a numerical precision issue. 

Currently, there is no pre-check of collinearity with the fixed-effects, so the variable is kept but the demeaning algorithm does not lead to a clean 0. Using higher precision levels, by changing the argument `fixef.tol`,  leads to values closer to 0 but not completely. I think I'll implement a pre-check of collinearity to avoid that kind of problem.

Usually, this does not lead to problems in the coefficient estimates. Except that in the data you sent me, between using `fixef.tol = 1e-6` (the default) and `fixef.tol = 1e-10`, this leads to changes in the coefficients, at the *4th significant digit* though.  In the vast majority of cases, the precision of the demeaning algorithm is of second order importance, but sometimes it matters.

From a user perspective, that the coefficients might change depending on the precision level, even if it's slightly, is not great. The problem is that I've not found a cheap way to test the elasticity of the precision level (of the algorithm computing the fixed-effects) on the estimated coefficients.

It's something I'll work on. If you have any idea, l take it!

## On different standard-errors with *lfe*

This is a **lfe** issue I think (I'm talking about version 2.8.5). 
Assume you estimate a model with 2 or more fixed-effects with `felm`, and you ask for clustered standard-errors.
At the moment there is *one* fixed-effect that is nested, the degrees of freedom associated to *all* the fixed-effects becomes 1.
So even if the other fixed-effects are not nested, their DoF is wiped out. I don't think this is how it should be.
For instance, this is not the case in **reghdfe**. The implementation in **fixest** follows **reghfe**.

The following cod illustrates the difference:
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "fe_1")
base$fe_2 = rep(1:15, 10)

est_feols = feols(y ~ x1 + x2 | fe_1 + fe_2, base)
est_felm  =  felm(y ~ x1 + x2 | fe_1 + fe_2 | 0 | fe_1, base)

se_feols = se(est_feols)
se_felm  = se(est_felm)

rbind(se_feols, se_felm)
#>                 x1        x2
#> se_feols 0.1603281 0.1180751
#> se_felm  0.1525025 0.1123118

# Making lfe's adjustment
n = nrow(base)
V = vcov(est_feols, dof = dof(adj = FALSE))
rbind(se_felm, se(est_feols, .vcov = V * (n - 1)/(n - 2 - 1)))
#>                x1        x2
#> se_felm 0.1525025 0.1123118
#>         0.1525025 0.1123118

# Here is fixest's adjustment
rbind(se_feols, se(est_feols, .vcov = V * (n - 1)/(n - 2 - 15)))
#>                 x1        x2
#> se_feols 0.1603281 0.1180751
#>          0.1603281 0.1180751
```

**Comment by alanpaulkwan** [comment]
Thanks for this. I was examining some work I am doing now, which I was curious to check.

Under single clustering, the most conservative was lfe 2.8.3, then fixest, then lfe 2.8.5 as your thread response might suggest.

Another interesting issue is double-clustering. My coefficients of interest were in the t-stat=6 range under lfe 2.8.3 which now... fixest says should be 12-ish, and the new lfe (2.8.5) says should be 9-ish. 

My first reaction would be to err on the side of the most conservative, but in many scenarios the researcher tries to argue non-significance is important. In any case, it seems like best to use lfe 2.8.3 for now if using lfe.

I think at some point one needs unit-tests across lfe, fixest and reghdfe on significance under peculiar clustering scenarios. Otherwise I need to basically check multiple packages to make sure I didn't screw it up.

**Comment by lrberge** [comment]
It could be great if you could devise a setup that encompasses all possible scenarios. Then we could compile the results on a webpage and update the results bi-annually (keeping track of past tested versions).

It should be only for the default values of the software, because users tend to not deviate from it (eg **lfe** allows different ways to make the small sample adjustments for 2+ clustering btw).

At some point, I'll have a "package down" website for the package. It could be hosted there.

**Comment by lrberge** [comment]
Just to say that in the new version of the package (0.7.1), the standard-errors are now computed à la reghdfe by default.

The comparison with lfe's SEs is up to date in this [vignette](https://cran.r-project.org/web/packages/fixest/vignettes/standard_errors.html).

Another point, now you can change the tolerance for dropping variables because of collinearity: the argument `collin.tol`. In the examples that you sent me, using `collin.tol = 1e-3` wipes out both `treatTRUE` and `postTRUE`.
