### ISSUE TITLE
No documentation for 'call_env' return value & potential inconsistency

### ISSUE THREAD

**Issue by s3alfisc** [lrberge/fixest#314]
Hi Laurent, 

Just a minor 'FYI' comment - I have noticed that the `call_env` return value is not documented in `fixest::feols()`. I am also wondering if I have spotted a minor inconsistency: `feols_object$call_env` and `terms(formula(object))` return *different* environments. Is this how it's supposed to be? :) 

Best, Alex 

```
library(fixest)
data(mtcars)

feols_fit <- feols(mpg ~ cyl, data = mtcars)

feols_fit$call_env
# <environment: 0x000001b7fe04f188>
environment(formula(feols_fit))
# <environment: 0x000001b7fe0eeae0>
environment(terms(feols_fit))
# <environment: 0x000001b7fe0eeae0>
```

**Comment by lrberge** [comment]
Hi Alex, thanks for the pointer, indeed documentation needs updating (many other stuff still isn't properly documented :-/), I'll fix this one (at least :-)).

That's not really a bug, it's just that I decided to save the environment in a specific slot of the object and not in the formula. One reason is that I modify formulas *a lot* in the internal code and keeping track of the original environment would have been plain horrible. 
Further, I cannot possibly fathom why in base R it has been decided that the environment of the call should be saved into the formula.... This is prone to hard-to-debug bugs. I think it would make more sense if the calling environment was just another outcome of the lm/glm objects. But there must be good reasons! :-)

I've seen your [SO post](https://stackoverflow.com/questions/72416652/expand-model-frame-within-lapply-map-environment-confusion-with-fixestf/72417124), and I'm sorry for the `expand.model.frame` not working. I wasn't aware of that since I don't use it but I'll try to make `fixest` objects compatible with it.

Just an example to illustrate the *environment in the formula* issue. Assume you create the formula to estimate your model with your own dedicated function. Here's a problem (the use case here is dumb but there are many real-world good reasons to create your own formula builder):
```R
# Creating a function to construct you formula out of character vectors
build_fml = function(y, x){
  txt = paste0(y, " ~ ", paste0(x, collapse = " + "))
  res = as.formula(txt)
  res
}

fml = build_fml("Sepal.Length", "Petal.Length")

# OK:
est = lm(fml, iris)
head(expand.model.frame(est, ~Sepal.Width))
#> est = lm(fml, iris)
#> head(expand.model.frame(est, ~Sepal.Width))
#>   Sepal.Length Petal.Length Sepal.Width
#> 1          5.1          1.4         3.5
#> 2          4.9          1.4         3.0
#> 3          4.7          1.3         3.2
#> 4          4.6          1.5         3.1
#> 5          5.0          1.4         3.6
#> 6          5.4          1.7         3.9

# Not OK, although completely legit:
x = iris
est = lm(fml, x)
head(expand.model.frame(est, ~Sepal.Width))
#> Error in model.frame.default(Sepal.Length ~ Petal.Length + Sepal.Width,  : 
#>   'data' must be a data.frame, environment, or list
```

The second call is 100% legit, yet you get an error that would send many off track.
