### ISSUE TITLE
Cragg-Donald, p-value incorrect  

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#318]
Cragg-Donald, p-value (cd.p) seems to be the same as Cragg-Donald (cd).

**Comment by grantmcdermott** [comment]
@waynelapierre Please always provide a MWE when raising issues. Even if the problem is trivial to reproduce, failure to provide a MWE just imposes extra times costs on Laurent, or anyone else that might want to help you really.  (See: [bug report guidelines](https://github.com/lrberge/fixest/issues/33).)
