### ISSUE TITLE
Memory management in fixest

### ISSUE THREAD

**Issue by simon-lowe** [lrberge/fixest#338]
Hi Laurent,

First of all, thank you so much for this package, it is truly amazing the public good you have created. 
I'm having some trouble with memory: I have a computer with 10gb of RAM and a dataset which takes 1gb of RAM. Today when I tried to run a TWFE regression, I got an error saying it could not allocate the memory. That seems like a lot of extra memory needed.

The concrete behavior is very strange: It gives me an error: cannot allocate vector of size 3.8gb (which is strange because it has 9gb) and then tells me that 4.85gb of memory are used, and gc() does not liberate the memory back to 1gb.

Sorry for the lack of reproducible code, it is on a secured access platform with admin data.

Thanks a lot,
Simon

**Comment by vincentarelbundock** [comment]
FWIW, that "could not allocate" is extremely common. Just put it in quotes in Google or in the StackOverflow search bars, and you will see a lot of discussion. You may also want to read the official R docs about memory management:

https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html

I'm not a `fixest` developer, but my guess is that it is extremely unlikely that they will be able to get actionable information from this issue, since there is no replicable example, and no information about memory use. One option may be for you to profile memory use with something like `profvis`, and then report back.

My guess is that this is either an enormous model, or that there is something locking memory use on your secured access platform. Diagnosing this properly would likely require access the model, the data, and the computer on which it is run.

**Comment by grantmcdermott** [comment]
FWIW a relatively common case for exploding memory is too many `i()` interactions in the formula RHS. I say "too many" b/c obviously this is model- and data-dependent. But there are much more efficient ways of handling these kinds of interactions and factors in the FE slot (i.e. after the `|`). See #168 for some related discussion and solutions.

At the least, while you can't post your data as part of a MWE, it would be helpful to see your model formula.

**Comment by lrberge** [comment]
Hi Simon! Memory issues are extremely difficult to diagnose. But IMO 10G is super small, and what you effectively have left to use within R is well below that amount (once you take out the OS, and other apps).

The main question is: is this `fixest` related? If you can perform the same estimation with alternative software, then it can be a problem with `fixest`, otherwise what you are estimating may simply be too much. 

For the background, to perform an estimation, you need several copies of the variables (e.g. the scores, the demeaned variable) and they are of size N. If your data is long and you use many variables, there's no doubt the need in memory is several times the size of your data set.

I'm closing this issue since it is not enough linked to fixest at the moment, feel free to open another one if you can demonstrate that the problem really comes from the software.

**Comment by simon-lowe** [comment]
Hi,

Thank you very much! It can't be said how amazing all your work on this. I've managed to make it work by being very frugal with what I have in the dataset. 

Thanks!

**Comment by lrberge** [comment]
Merci Simon! :-)
