### ISSUE TITLE
Collinear variables re-introduced when adding fixed effects

### ISSUE THREAD

**Issue by turbanisch** [lrberge/fixest#354]
When estimating a trade model using `fepois`, one variable gets dropped due to multicollinearity in the presence of 3 fixed effects but curiously reappears when a fourth fixed effect is introduced. 

Our dataset has the dimensions `origin`, `destination`, `time` and `product`. The four fixed effects we would like to include are `destination^time + origin^time + product^time + destination^origin^product`. The explanatory variable in question varies only across `destination` but not within, so I expected it to be collinear to the fixed effects. However, it shows up (with a super low t-value) in the regression output. When I remove one of the fixed effects (e.g. `destination^origin^product` or `product^time`), the variable gets absorbed as expected. 

Replicating the same regression with Stata's `ppmlhdfe`, the variable in question is removed due to collinearity even in the presence of all four fixed efffects. 

I want to apologize in advance for the lack of a reproducible example - the issue occured in an ongoing research project with a rather big dataset (~4M rows) and I did not manage to reproduce the issue with any of the datasets built into `fixest`. Perhaps you could nevertheless leave a quick comment regarding my expectations and on whether the number and structure of our fixed effects could lead to any problems?

**Comment by lrberge** [comment]
Hi, it seems to me that there's no problem. 

Collinear variable removal is no exact science and is present only for convenience reasons. 
Depending on the method used to identify collinear variables, you may have different variables that end up removed, the results however **on the non collinear system** should be identical (coef + SE).
The only thing that matters is the non collinear system, and it should be immune to which variable ends up removed. 

Indeed, if one variable is removed, this means that it is within a collinear system--so that any variable in that system shouldn't be interpreted (because it could have been them which would have been removed!). 
IMHO, it is the responsibility of the user to estimate a model without collinearity, or ensure that the collinearity only affects variables that are controls (not to be interpreted). 

So back to your example: if all the variables of interest (which aren't in a collinear system) are identical, then there's no problem at all. It's just cosmetic.

**Comment by turbanisch** [comment]
Thank you so much for this lightning-fast response and the clarification! Indeed, the point estimates are virtually the same as Stata's and the standard errors only differ marginally from those of Stata and from the model without the collinear variables estimated in R. 
The discrepancy to Stata is likely due to the fact that R keeps an additional 2 observations in the regression. As a result, two of the fixed effects have two additional levels (compared to Stata). I'm wondering if this could possibly be due to different rounding of floating point numbers?

**Comment by lrberge** [comment]
You can remove singletons with `fixef.rm = "singleton"`. That's the default in Stata (the 2 obs.). I'll make it the default in `fixest` too one I've improved the algorithm.
The additional observations only impact the value of the SEs (since the DoFs are different).

Which variable is dropped b/c of collinearity really isn't an issue and that is normal that there can be differences across software. There are even differences within software! For instance, in `fixest` the order of the variables matter since the algorithm to expel collinearity is sequential.
