### ISSUE TITLE
Get no. of clusters (G)

### ISSUE THREAD

**Issue by grantmcdermott** [lrberge/fixest#39]
Hi Laurent,

One nice thing that the **reghdfe** package in Stata does is display the number of clusters. For example, here's what you get if you run the model from your "standard errors" [vignette](https://cran.r-project.org/web/packages/fixest/vignettes/standard_errors.html). (Note that I'm clustering twoways here just to demonstrate a slightly more complicated case.)

![reghdfe](https://user-images.githubusercontent.com/10285037/89484203-d50e5d80-d752-11ea-99af-9931f074a551.png)

So we actually see quite a bit of information about how things were clustered and the associated DoF adjustments (including the bottom panel, which is pretty detailed). For the purposes of this issue, though I'm mostly interested in the line that tells us: 

> ` (Std. Err. adjusted for **4** clusters in id time)`. 

Sticking with the formal definition, I guess we would refer to the number 4 as *min(G)*.

Is it possible to retrieve this same information with **fixest**? I know that we can get quite a bit of information with, say, `attributes(vcov(est))`, but I can't see how to get this *G* number. (Apologies if I missed it!)

FWIW, I'm mostly asking because I frequently see this information presented at the bottom of regression tables in econ journals... and even more frequently get asked "how big my effective sample is" during presentations. It would be very helpful have it available in the return model object... or even added to `etable()`.

Thanks, as ever.

**Comment by lrberge** [comment]
Hi Grant, thanks again for the feedback!

You're totally right, this number isn't accessible, and I agree, it would be useful to be there. 
Now the question is: what's the best way to include it?

I don't think it can be in the estimation object directly since it's a feature specific to the VCOV--although it could be inserted directly in the object post summary. 

I was thinking to create a function `fitstat` that can compute various measures (including the f-stat, the likelihood ratio, etc). The "G" could be included in there (although it would be necessary to apply the fitstat function post-summary in that case). 
Then in `etable`, in the argument `fitstat` you could leverage any value computed in the function `fitstat`, ensuring a direct integration. 

Not sure yet of the optimal design, please let me ponder that a bit. Btw, I'm taking 10 days off, maybe it'll help! 
Don't hesitate if you have other suggestions or suggestions for the way to implement it.

**Comment by lrberge** [comment]
Hi Grant, it took a while, but finally I think I've included what you want. 

So there's the `fitstat` function now that includes this *G* value. So far that function is an empty shell (since only G and the over-dispersion parameter for the negbin are there), but more stuff will come (especially that the compatibility with the other functions is easy to maintain).

I didn't find a good display name for G, so I kept it to G. If you have ideas for display names, I take it!
Also, when clustering is not performed, it returns G == nobs, do you think it is correct? (Or should I include a small sample correction in it? Or should it be NA? I have no clue!)

```R
library(fixest)
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

est = feols(y ~ x1 | species, base)
fitstat(est, "G")
#> [1] 3

etable(est, summary(est, se = "s"), fitstat = ~ . + G)
#>                                   est summary(est, se ..
#> x1                  0.8036** (0.0714) 0.8036*** (0.1063)
#> Fixed-Effects:      ----------------- ------------------
#> species                          Yes                 Yes
#> ___________________ _________________ __________________
#> S.E. type              1-way: species           Standard
#> Observations                      150                150
#> R2                            0.72591            0.72591
#> Within R2                     0.28115            0.28115
#> G                                   3                150
```

**Comment by grantmcdermott** [comment]
Brilliant, thanks Laurent!

RE: names. I think "G" is fine if it is well described in the documentation... certainly, as a variable in the return first object. 

But I would err on the side of calling it "Effective clusters" or something similar for any regression regression table output. ("Num. eff. clusters"?) I can handle that on the broom/modelsummary side, though.

**Comment by lrberge** [comment]
Thanks for the reply! 

I'll take care of adding more information in the related help page in the next release.

I'm closing then! :-)
