### ISSUE TITLE
Minor bug: `^` causes trouble in `terms.formula`

### ISSUE THREAD

**Issue by karldw** [lrberge/fixest#4]
I noticed that using `^` can cause issues with formula parsing. Here's the case I tripped over, with `stats::terms.formula` called [indirectly](https://github.com/lrberge/fixest/blob/master/R/MiscFuns.R#L1051) by `fixest::r2`. I think this is a bug, though let me know if I'm misinterpreting.

``` r
library(fixest)

gravity_results <- feglm(
  Euros ~ log(dist_km) | Origin ^ Destination + Product ^ Year, 
  data=trade
)
r2(gravity_results)
#> Error in terms.formula(tmp, simplify = TRUE): invalid power in formula
```

<sup>Created on 2019-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lrberge** [comment]
You unveiled a bug in update. I cannot use the function `update(old_fml, new_fml)` to update the formula when it contains FEs of the form `var1^var2` because `update.formula` would throw an error when faced with this unconventional writing. I have to do it manually using character strings instead -_-. I'll fix it, thanks.
