### ISSUE TITLE
Possible to reduce size of fixest models?

### ISSUE THREAD

**Issue by duncanhobbs** [lrberge/fixest#41]
Thanks for the great package.

Is there a way to specify which objects to return from a fixest model?

For example can I choose to return the fitted values, sum of the fixed effects or matrix of the scores or not?

I am running a feols model with about 40 million observations that looks like this

`est_did_emp_500_col1 = feols(log(employment) ~ small_business_500:post | small_business_500 + post, data=dfr_emp_ind_sample)`

I am finding that the returned model objects take up a lot of space.

```
object.size(est_did_emp_500_col1)
1962264560 bytes
```

I looked at the size of each component:

```
lapply(est_did_emp_500_col1,object.size)

$nobs
56 bytes

$fml
1176 bytes

$call
1736 bytes

$method
112 bytes

$fml_full
1736 bytes

$nparams
56 bytes

$fixef_vars
200 bytes

$fixef_id
392379704 bytes

$fixef_sizes
368 bytes

$obsRemoved
358296 bytes

$iterations
56 bytes

$coefficients
304 bytes

$residuals
392378704 bytes

$multicol
56 bytes

$sumFE
392378704 bytes

$fitted.values
392378704 bytes

$scores
392378872 bytes

$hessian
224 bytes

$sigma2
56 bytes

$cov.unscaled
672 bytes

$coeftable
1456 bytes

$se
536 bytes

$sq.cor
56 bytes

$ssr_null
56 bytes

$ll_null
56 bytes

$ssr_fe_only
56 bytes

$ll_fe_only
56 bytes
```

Are there other good ways to reduce the size of these models?

Thanks.

**Comment by lrberge** [comment]
Hi, so far there's no way.

The most problematic lads are: `scores` (N x K) and `fixef_id` (N x G).
Then you have some doubles of length N: `sumFE`, `fitted.values` and `residuals`.

So far, what `summary.fixest` does is computing the SEs and modifying the coefficients table (`coeftable`) accordingly--leaving the rest of the object untouched. 
I don't think it's a good idea to drop the previously mentioned objects from the estimation result because it's stuff that cannot be easily recovered and are needed in some methods. But it can be a good idea to drop them from the `summary`. In the next version I may drop by default the previously mentioned objects from the output of `summary` (still have to think it through though).

In the meantime, it's very easy to circumvent the problem:
```R
> base = iris
> names(base) = c("y", "x1", "x2", "x3", "species")
> library(fixest)
> 
> summary.fixest = function(...){
>     res = fixest:::summary.fixest(...)
>     res[c("scores", "fixef_id", "sumFE", "fitted.values")] = NULL
>     res
> }
> 
> est = feols(y ~ x1 + x2 | species, base)
> # original:
> object.size(fixest:::summary.fixest(est))
#> 19880 bytes
> # light one:
> object.size(summary.fixest(est))
#> 11832 bytes
> # same results:
> etable(a, b)
#>                                       a                  b
#> x1                    0.4322** (0.1613)  0.4322** (0.1613)
#> x2                   0.7756*** (0.1265) 0.7756*** (0.1265)
#> Fixed-Effects:       ------------------ ------------------
#> species                             Yes                Yes
#> ___________________  __________________ __________________
#> Observations                        150                150
#> S.E. type: Clustered        by: species        by: species
#> R2                              0.86331            0.86331
#> Within R2                       0.64151            0.64151
```
This way you don't need to change an inch of your code (note that so far you shouldn't drop `residuals` since they're used for the R2). You can also apply the same trick to `feols` if you wish, but then some methods may not work.

**Comment by lrberge** [comment]
Hi, just to note that in version 0.7.0 `summary` accepts the argument `lean`. If TRUE, then all values of length N are cleaned.
