### ISSUE TITLE
order in etable() does not work with dict

### ISSUE THREAD

**Issue by sleeubc** [lrberge/fixest#42]
Thank you for writing this fantastic package. This is great contribution to empirical economist community.

While I was working with etable(), I found that the order option in etable() does not work when dict option is specified. Could you look into this please?

```
library(fixest)

model <- feols(mpg ~ cyl + disp, data= mtcars)

etable(model, order = c("disp", "cyl"))

# order does not work with dict, whether it uses variable name or label.
etable(model, order = c("disp", "cyl"), dict = c(disp = "$DISP$"))
etable(model, order = c("$DISP$", "cyl"), dict = c(disp = "$DISP$"))
```

**Comment by lrberge** [comment]
Thanks for the words, I'm really happy you find it useful! :-)

Actually everything works as expected.

The argument `order` takes in [regular expressions](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/regex), and since `$` is a special character in regular expressions it needs to be duly escaped (and yes: you need two backslashes). 
Note that you can also use regular expressions on the **original variable names** by using `%` as the first character. It's unfortunate there's been a glitch in the documentation of `etable` that prevented this section to be displayed, but I now have corrected it. 

Here's how it works:

```R
> library(fixest)
> model <- feols(mpg ~ cyl + disp, data= mtcars)
> # Using '%' to access original name
> etable(model, order = c("%disp", "cyl"), dict = c(disp = "$DISP$"))
#>                                   model
#> $DISP$              -0.02058. (0.01026)
#> cyl                    -1.587* (0.7118)
#> (Intercept)            34.66*** (2.547)
#> ___________________ ___________________
#> Observations                         32
#> S.E. type: Standard            Standard
#> R2                              0.75957
#> Adjusted R2                     0.74298
> # Using a regular expression => requires escaping the $
> etable(model, order = c("\\$DISP\\$", "cyl"), dict = c(disp = "$DISP$"))
#>                                   model
#> $DISP$              -0.02058. (0.01026)
#> cyl                    -1.587* (0.7118)
#> (Intercept)            34.66*** (2.547)
#> ___________________ ___________________
#> Observations                         32
#> S.E. type: Standard            Standard
#> R2                              0.75957
#> Adjusted R2                     0.74298
```

**Comment by sleeubc** [comment]
The % approach is smart.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by sleeubc** [comment]
Thank you. The % approach is smart!


Sent from my Samsung Galaxy smartphone.



-------- Original message --------
