### ISSUE TITLE
feols computes infeasibly small standard errors

### ISSUE THREAD

**Issue by NickG-e61** [lrberge/fixest#438]
[exampledata.csv](https://github.com/lrberge/fixest/files/12469689/exampledata.csv)

As an example, running the following line on the linked dataset (where DV and EV are randomly generated) reports a p-value of 1.8e-15. There should be plenty of degrees of freedom. 

feols(DV ~ EV | state + as.factor(month), data=exampledata)

I'm also getting funny looking standard errors in other cases, e,g, converting a factor to a set of dummies and then getting the same standard error on every dummy coefficient. Can give more details if you'd like.

**Comment by lrberge** [comment]
Hi, and thanks for making the data available, but could you report the output you are referring to with ready to go code?

Did you compare with other software (lm/lfe/Stata/Julia)?

**Comment by NickG-e61** [comment]
Sure, the output is attached, for fixest and for lfe.

![image](https://github.com/lrberge/fixest/assets/132252580/31b03a21-96bf-489f-8543-731439fb5ef5)

**Comment by lrberge** [comment]
Thanks, now it is clear:
- it's because the standard-errors are clustered on a cluster of two values

By default, if the argument `vcov` is not provided, `fixest` clusters the SEs wrt the first fixed-effect, here this is `state`. 
The current `lfe` SEs are "iid" so the comparison doesn't hold.

You need to know what kind of standard-errors you want ("iid", "heteroskedasticity-robut", "clustered"?) and then pass it into the [`vcov`](https://lrberge.github.io/fixest/articles/fixest_walkthrough.html#the-vcov-argument) argument.
The problematic SEs come from clustering with such a few number of clusters (it shouldn't be done).

**Comment by NickG-e61** [comment]
OK, thanks for clarifying. Since there is no default argument for vcov, my natural assumption was that it computes standard errors based on a spherical errors assumption. Others might assume this too.

**Comment by lrberge** [comment]
Sure. The use case is individual panel data. 

The type of SE is clearly stated though:
![image](https://github.com/lrberge/fixest/assets/43536394/0b1424d0-59c2-4492-b1c3-b7e76c30c61b)

Closing then. Thanks for reporting the outputs.
