### ISSUE TITLE
probitFE and logitFE implementation

### ISSUE THREAD

**Issue by apoorvalal** [lrberge/fixest#49]
Hello,

Thanks for the great package; the speed gains and well-documented vignettes have been a boon. 
I was wondering if there are any plans to / there be any interest in an implementation of the Ferndandez-Val - Weidner split-sample/debiasing approach to two-way FEs in probit and logit models in the package. 
+ Theory https://arxiv.org/abs/1311.7065
+ Stata https://arxiv.org/abs/1610.07714
I'd be happy to take a crack at it [although I'm less confident about making it run fast] by forking the repo.

**Comment by lrberge** [comment]
Hello and thanks for the words! :-)

The short and incomplete answer is *yes*. The complete answer contains a disappointing *but*: but not before a year or two. 

I really do want to include this kind of tools because so far the raw FE logit/probit are, indeed, hardly useful due to the presence biases. This is however very low priority for me because I don't use these models in my day-to-day research work. 

To give you a hint of the stuff I want to finish before coming to that:
 - finishing a massive overhaul of the internal demeaning algorithm to accommodante closed form solutions for variables with varying slopes (I should end that soon),
 - implementing some staggered DiD tools that have been recently developed (mostly because I'll use them in my papers),
 - implementing IV estimations,
 - implementing marginal effects, in a way that is completely integrated with the exports.

And since I also need to move on to work that is more important career-wise... well, it'll take some time before I come to it!

#### Way to go?

It would be fantastic if you could implement it. But it looks like a big job to get close to the Stata implementation. Also I can't guarantee to include it in the package directly--since I'm a bit of a control freak, I need to ensure it gets embedded with other functions (print/exports/vcov and maybe others) and that users can't misuse the new function (and it takes time to check :-( ). 
Or maybe differently, what do you think?

#### Other comments

By the way, do you know how to get clustered standard-error? Because we need the score for each observation, is it well defined in the jackknife? (Or we just compute it at the jackknife-point estimates?) I'm asking because I've never thought about it. 

If you do it, I can try to have an (incomplete) marginal effects function ready (although that won't be before a few months :-( ).

Just a comment: Tables 1 and 2 of the Stata paper are unfortunately not really convincing since all results really look the same :-( and it seems hard to choose between the different models. Are there rules of thumbs to choose between them?

**Comment by apoorvalal** [comment]
Agree re: relatively low-priority for most use cases; I find the marginal effects to be pretty comparable, but some referees are morons.
I'll fork the repo and give it a shot; at the very least it looks like a fun little programming challenge. I'm not really sure about clustering in this setting either. 

RE: tasks - those all look very useful. What staggered DiD methods are you looking to implement? Goodman-bacon weights should be relatively easily doable. Also is Chaisemartin WFE in the pipeline?

**Comment by lrberge** [comment]
_On giving it a shot:_ Fantastic!

_On staggered did:_ I was thinking at least GB and de Chaisemartin & d'Hautefeuille. Then maybe Abraham & Sun, Callaway & Sant'Anna, and Imai & Kim, but for these last 3 I didn't go through the theory yet.

**Comment by lrberge** [comment]
Just for the update, I won't implement GB nor CH (2020) nor CS (forthcoming), but Sun and Abraham (forthcoming) will be there in the next version.
