### ISSUE TITLE
`update.fixest` has issues when another object has the same name as input data

### ISSUE THREAD

**Issue by karldw** [lrberge/fixest#5]
I noticed that `update.fixest` has issues when the data used to estimate is not in scope. If there are no other objects with the same name, you get a helpful error message, but if there are, it's more confusing.

Here's a demo where `df` stops referring to the trade data and starts referring to the `stats::df` function, causing trouble. 

``` r
library(fixest)
fn <- function() {
  df <- trade
  feglm(Euros ~ log(dist_km)|Origin+Destination+Product+Year, data=df)
}

x <- fn()
r2(x)
#> Error in if (n_old != n_new) {: argument is of length zero
```

<sup>Created on 2019-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If I hadn't called the data `df` but rather `trade2`, I would have gotten the error:
```
Error in update.fixest(x, . ~ 1 | ., glm.tol = 0.01, fixef.tol = 0.001,  : 
  To apply 'update.fixest', we fetch the original database in the parent.frame -- but it doesn't seem to be there anymore (btw it was trade2).
```

The issue is here:
https://github.com/lrberge/fixest/blob/9abf86b077c933b6770ea064253a7fd605a18f40/R/MiscFuns.R#L6537-L6542

This would also be a problem if people had multiple datasets with the same name, and were using function boundaries to keep them straight. One solution is to have the model object hold onto a copy of the data, which `felm` and `lm` do, but that can be its own headache for memory use.

**Comment by lrberge** [comment]
Thank you very much for the in-depth analysis of the package! This is super useful! 

There are several separate points to be addressed in your issue.

The fact that the data is not in copy in the object returned is indeed on purpose. `fixest` objects contain already K + G vectors of lengths N (the scores and the FEs): this is to ensure that when the clustered SEs are computed, it's never messed up.

In some **utility functions** (`update`, `vcov` [for clustering with vars not used as FEs], `fixef` [to get the coefficient for varying slopes only], and `collinearity`), I do (try to) fetch the data from the call for convenience reason, so that the user doesn't have to bother with giving the original data while ensuring a small memory footprint. Note that the function `r2` is not part of this group.
Problem:
   -1) I've never thought of the situation where `fixest` is called within a function, messing up the fetching once the **utility functions** are called in the upper frame.

The bug regarding the function `r2` is of another type. Actually the within R2 for `feglm` functions is a pain in the neck. It requires to re-estimate the model with FEs only since this is not a by-product of the original estimation (contrary to `femlm` or `feols`). This means increased computing time in general, and a call to `update` in particular within the function `r2`.
Problem:
   -2) For the reason described in 1), `r2` throws an error when `feglm` was initially called within a function due to the call to `update`.

Regarding the error `#> Error in if (n_old != n_new) `. 
   -3) This is clearly a bug that I will correct, the error message should be explicit.

Potential solutions to 1) and 2):
Regarding 2): obtaining the within-R2 of an estimation should definitely be self contained, without requiring external information. So I'll add the dependent variable as an output of all `feglm` estimations, and drop the call to `update` within `r2`, using `feglm.fit` instead.

Regarding 1): Taking 2) as solved, the potential problems are quite reduced because of the limited scope of the utility functions causing problems (e.g. using `update` on a function that was used internally in another function is odd, same for `vcov` when clustering with variables not used as fixed-effects from the data existing within a function). Is it worth to add the full data just for them? I'm agnostic but tilting slightly toward no. Here's what can be done (the points are not exclusive):
a) status quo
b) adding the variables with varying slopes as an output (solves the `fixef` problem) [actually I'm strongly in favor of implementing it]
c) add an argument `save_data` which defaults to `FALSE`
d) add a possibility to set what is saved globally: e.g. `setFixest_save(...)`, with in `...` the data, and any other not indispensable stuff (e.g. the expected predictor, etc...), so that some users don't have to set `save_data = TRUE` all the time -- or if they wish they can make the output of `fixest` lean.
e) If the data is to be saved: should it consist of only the variables used for the estimation? If so, it would not solve the problem of `update` and `vcov` requiring other variables from the full data set. If the full data set is to be saved, then it can be a huge memory burden.

Any opinion?

**Comment by karldw** [comment]
Thanks for the very well written package! 
I'll need to think a little about the points you made, but let me loop in @grantmcdermott who might have opinions.

**Comment by lrberge** [comment]
Actually I made up my mind :-)

After correcting 2) and 3), I'll only include the variables with varying slopes in the returned object (point b), this will make a call to `fixef` self-contained.

I am not planning to include a copy of the data in the returned object. The reason is that the extra functionalities it would allow are way too limited to justify it (it's even not worth a new argument `save_data` I think). 

Thanks again for the very detailed issue, I'll fix it in the coming week.

**Comment by karldw** [comment]
Sounds great! Thanks again.
