### ISSUE TITLE
undefined reference error

### ISSUE THREAD

**Issue by amarbler** [lrberge/fixest#50]
Hi,

thanks for setting up the FIXEST package, it's really a huge time saver and intuitive to use!

I just wanted to update to the latest github version using devtools::install_github(), unfortunately I get the following errors:

RcppExports.o:RcppExports.cpp:(.text+0x1b26): undefined reference to `get_nb_threads()'

RcppExports.o:RcppExports.cpp:(.text+0x1d49): undefined reference to `setup_fork_presence()'

RcppExports.o:RcppExports.cpp:(.text+0x1e89): undefined reference to `is_in_fork()'
...
ERROR: compilation failed for package 'fixest'

I suspect the errors may be related to the recent changes in "RcppExports.R"?

I tried to update to the latest version on two different devices one running on windows and the other on linux, resulting in the same error.

**Comment by lrberge** [comment]
Hi, thanks for using it!  :-)

This problem is, I confess, recurrent and pertains to the way I develop the package, since I don't need this file to make things work. That means that I need to regenerate it explicitly... so I often forget!
If it happens again that you need the dev version and this file is not updated, just drop me a line, I'll regen it and push it asap.

But by now, the current GH version should be working, no?

In any case, I'll publish the new version to CRAN in a week or two, after I finish a few things.
