### ISSUE TITLE
etable format style

### ISSUE THREAD

**Issue by gbekes** [lrberge/fixest#60]
Thanks for the great package.

etable is awesome because it is so simple.

Minor idea:  any chance to add a pandoc format style like in [pander](http://rapporter.github.io/pander/#markdown-tables)
(Maybe it's there and did not find it...)
Thanks!

**Comment by lrberge** [comment]
Thanks for the simplicity compliment! It's been quite some effort to make it simple! :-D

Regarding `pandoc`, in my opinion, it's out of scope to include that kind of thing in the package. 

Yet since the function `etable` returns a data.frame, so it can be fed directly to pander:

```R
library(fixest)
library(pander)
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
res = feols(y ~ x1 + x2 | species, base)
m = etable(res)
pandoc.table(m)

#> ---------------------------------------------
#>           &nbsp;                  res
#> -------------------------- ------------------
#>           **x1**            0.4342 (0.1652)
#>
#>           **x2**                  mmm
#>
#>     **Fixed-Effects:**      ----------------
#>
#>        **species**                Yes
#>
#>  **___________________**    ________________
#>
#>  **S.E. type: Clustered**     by: species
#>
#>      **Observations**             147
#>
#>           **R2**                0.85981
#>
#>       **Within R2**             0.64136
#> ---------------------------------------------
```

So I've added an argument: `postprocess.df` which applies a postprocessing to the result. The following leads to the same result:

```R
etable(res, postprocess.df = pandoc.table)
```

Finally, since I've added it in the option setting function, you can just set it once and then forget about it:
```R
setFixest_etable(postprocess.df = pandoc.table)
etable(res)
```

By the way, since it's related, I've added the argument `style.df` which controls the look of the table.

```R
etable(res, style.df = estyle.df(fixef.title = "", fixef.suffix = " FE"))
#>                                   res
#> x1                    0.4322 (0.1613)
#> x2                   0.7756* (0.1265)
#> species FE                        Yes
#> ____________________ ________________
#> S.E. type: Clustered      by: species
#> Observations                      150
#> R2                            0.86331
#> Within R2                     0.64151
```

And you can also set it permanently with `setFixest_etable`.


All these changes will be available in version 0.8.0. And it's not yet on GH (I currently have some git issues...).

**Comment by gbekes** [comment]
OMG, this is super!!! Thanks a lot.  Great idea re feeding it to pander, too!

**Comment by lrberge** [comment]
Done! It's pushed! 642f2289da4772455afb5b900178de4e71ea1bfc

Note that it's still the dev version, so there may be some bugs around.

**Comment by lrberge** [comment]
I'm closing then! Thanks again for the suggestion.
