### ISSUE TITLE
Sideways table & Scalebox

### ISSUE THREAD

**Issue by AndreWal** [lrberge/fixest#62]
Hi,

fixest is a really great package! I would like to ask if it's possible to add functions allowing sidewaystables and scaling (e.g. scalebox) when exporting tables to latex?

Merci!

**Comment by lrberge** [comment]
Hi, and thanks for using!

I've got some request to add more Latex-related features lately. Not sure I can include everything since often the queries are quite specific. 

So instead, I've added postprocessing functions. This way the user can set up its own postprocessing function and include whatever s/he fancies. 

By default the function `etable` returns a character vector if `tex = TRUE`. So the user can catch it and apply ad hoc modifications. Further I've added two tags that identify the start and end of the tabular to make it easier. 

In your case, we could do:

```R
# Setup your postprocessing function

extratex = function(x, sideways = FALSE, scalebox = NULL){
    check_arg(sideways, "logical scalar")
    check_arg(scalebox, "NULL numeric scalar GT{0}")

    if(sideways){
        x = gsub("{table}", "{sidewaystable}", x, fixed = TRUE)
    }

    if(!is.null(scalebox)){
        qui_start = grepl("%start:tab", x)
        qui_end = grepl("%end:tab", x)

        x[qui_start] = paste0("\\scalebox{", scalebox, "}{\n")
        x[qui_end] = "}\n"
    }

    x
}

# Let's try it!
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
est = feols(y ~ csw(x1, x2), base)
etable(est, postprocess = extratex, sideways = TRUE, scalebox = 0.7, title = "This is a test", tex = TRUE)
#> \begin{sidewaystable}[htbp]
#> \centering
#> \caption{This is a test}
#>  \scalebox{0.7}{
#>  \begin{tabular}{lcc}
#> \tabularnewline\toprule\toprule
#>  Dependent Variable:&\multicolumn{2}{c}{y}\\
#>  Model:&(1) & (2)\\
#>  \midrule \emph{Variables}&   &  \\
#>  (Intercept)&6.526$^{***}$ & 2.249$^{***}$\\
#>   &(0.4307) & (0.2316)\\
#> x1&-0.2234 & 0.5955$^{***}$\\
#>   &(0.1414) & (0.0647)\\
#> x2&   & 0.4719$^{***}$\\
#>   &   & (0.0167)\\
#>  \midrule \emph{Fit statistics}&  & \\
#> Observations & 150&150\\
#> R$^2$ & 0.013823&0.840178\\
#> Adjusted R$^2$ & 0.007159&0.838003\\
#>  \bottomrule\bottomrule\multicolumn{3}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
#> \multicolumn{3}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
#>  \end{tabular}
#>  }
#>  \end{sidewaystable}
```

As you can see, the function `etable` catches the arguments of the custom postprocessing function (since `sideways` and `scalebox` are **not** `etable` arguments). 

You can even set the function globally, allowing you very natural calls:
```R
setFixest_etable(postprocess = extratex)
etable(est, sideways = TRUE, scalebox = 0.7, title = "This is a test", tex = TRUE)
```

Now  it's like the number of arguments of `etable` had just been augmented.

Is it OK? I know it's a bit of coding, but it adds lots of possibilities without complexifying the `etable` function.

**Comment by AndreWal** [comment]
Thanks for your effort! However, I can't reproduce your example because I can't find the csw() function. And using "x1+x2" instead "csw(x1, x2)" returns the following error:

`Error: in etable(est, postprocess = extratex, sid...:
 In argument '...', each element must be either: i) an object of class 'fixest', or ii) a list. Problem in the second
element: i) the object is not of the appropriate class (instead it is of class function), or ii) it is not a list
(instead it is a function). `

Same probem with the data I use.

Merci!

**Comment by lrberge** [comment]
That's normal: use the dev version (which is almost stable now) it should work!

By the way, for clarity, I changed the name of the argument `postprocess` into `postprocess.tex` (that's because there's a `postprocess.df` too).

**Comment by lrberge** [comment]
Hi it should work with the new CRAN version. I'm closing then.
