### ISSUE TITLE
some minor questions

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#64]
I just found your fixest package, and it is going to be my favorite r package. I have some minor questions about this package. 

First, your benchmark seems to miss clustering effects. It would be great if you could test both fixed and clustering effects like this one: 
https://github.com/FixedEffects/FixedEffectModels.jl/blob/master/benchmark/result.png

Second, I think the default latex output should use booktabs rules instead of double or single hlines. 

Third, is there a way to report the t-values instead of standard errors beneath the coefficients in the latex output?

**Comment by lrberge** [comment]
Hi and thanks for using it!

  1. I actually didn't want to push the benchmarks in favour of my package, that's why I didn't include clustering.  But typically, once the estimation is done, the clustering of the SEs is almost instantaneous--so only the competing software would suffer. Although it can be interesting to have it, I don't think I'll include it in order not to clutter the results.  

  2. I know the booktabs' author rule of *never use double lines*. But it's just a matter of taste in my opinion and I don't dislike it. By the way, go tell the QJE that their tables suck ;-). 
In any case, your suggestion is covered already. I'll release a new version soon and you'll be able to use `style.tex("aer")` to obtain a neat table with top/bottom rule *a la* AER.  It may even become the default style since I'm tired of the old look.

  3. Yes! `coefstat = "tstat"`

**Comment by waynelapierre** [comment]
Thanks for the clarification! Speaking of booktabs rule vs. hline, it is more than a matter of taste. In my case, I typically need to heavily edit all latex tables after they are exported by R. The space between hline and the texts surrounding it could be a problem sometimes. A lot of \\[ ] and \vspace{} make it difficult for editting.

**Comment by lrberge** [comment]
OK, I didn't get the tabular technicalities from your first message. I better understand now!
