### ISSUE TITLE
OLS result different from lm

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#74]
```
require(foreign)
df.petersen <- read.dta("http://www.kellogg.northwestern.edu/faculty/petersen/htm/papers/se/test_data.dta")

#OLS
summary(lm(y~x, data=df.petersen))
require(fixest)
summary(feols(y ~ x, data = df.petersen))

```
For the coefficient of x, lm yields 1.03483 and feols yields 1.03480. The difference of 0.00003 seems trivial, but I would like to understand it so I can better learn your fixest package. 

If we calculate the White standard errors, the difference still exists. 
```
require(sandwich)
require(lmtest)
model <- lm(y~x, data=df.petersen)
coeftest(model, vcovHC(model, type="HC0"))
summary(feols(y ~ x, data = df.petersen, se = "hetero"))
```

However, the lfe package yields the same result as lm does. 

```
require(lfe)
summary(felm(y ~ x, data = df.petersen), robust = TRUE)
```

**Comment by lrberge** [comment]
This is because I use the normal equation to solve the linear system. On the other hand `lm` uses a QR decomposition which is known to be numerically more stable. And if I'm not mistaken `lfe` uses `lm` once the variables are centered, hence the absence of difference.

The differences should be negligible though. The only situations where it can matter is when you have many almost collinear variables and are interested in the coefficient of a variable that is in the poorly conditioned system.
