### ISSUE TITLE
Tex Table Number of Digits 

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#75]
I found that the digits parameter of etable different from other packages. For xtable and stargazer, digits indicate the number of digits to show after zero. For fixest, digits seem to indicate the total number of digits to show, which seems uncommon based on my personal experience. 

In addition, the digits parameter seems to have no effect on the R squared value.

**Comment by lrberge** [comment]
Indeed, this is the number of significant digits. That's because I don't like to have coefficients of the like of `0.00` in tables, which you would get if you use `digits = 2` in the software you mentioned. 

You're right, the fit stats are not affected by the argument `digits`. I don't know if it should. I may add another argument for that later (`digits.stat = digits`). 

Maybe I could also allow a finer control of this rounding parameter (to get the behavior you mentioned). The problem is that I don't want to bloat the code with too many arguments. So I have to think to an economical design. I'll let you know!

**Comment by waynelapierre** [comment]
I totally agree that making numbers have the same number of digits looks nice. However, when the stars are added, numbers with the same number of digits after zero look better.
