### ISSUE TITLE
Another ^ bug, now with predict.fixest

### ISSUE THREAD

**Issue by hanewinckel** [lrberge/fixest#8]
predict.fixest returns a warning and preditcs all NAs when fixed-effects/cluster_vars are used with a "^" (observed for a feglm):

![Annotation](https://user-images.githubusercontent.com/44176226/69762341-f0db5180-1137-11ea-9bb9-0f944b2ba130.png)

I tinkered with line 5627 of MiscFuns.R as parse did not handle the "^" by doing a gsub of ^ to , and wrapping it in "paste(...,sep='_')" to make the fixed effects "match" those produced by model fit. This caused cluster_current_unik to correctly return an empty set on line 5628. But there's obviously more to this problem as various other parses involving "^" happen down the line.

I'm rambling (hopefully helpfully). But for now, the only workaround I can think of is to create a new factor variable with paste0(factor1,"_",factor2,"_"...).

Really enjoying this package!

**Comment by lrberge** [comment]
Yep, dealing with the ^ is tricky. But since I've dealt with it in some other place, this is an easy fix!

Although I did torture myself to try to think to all possible situations regarding the core functions, this was less the case for the auxiliary methods. Well spotted!

(By the way, I didn't remember I also took care of the case of combined FEs + varying slopes. Cool. :-) )

Glad you like it! :-) And thanks for the feedback!
