### ISSUE TITLE
Notes option under table in "etable"

### ISSUE THREAD

**Issue by Annyan233** [lrberge/fixest#87]
It seems that the notes option is not working in "etable".
I used it this way:
table<-etable(model,stage = 1,se="cluster",fitstat=~ivf1,digits = 3,sdBelow=TRUE,
                                     notes=c("xxx"))
Could you please provide an example to use this option correctly if I used it wrong?
Thank you!

**Comment by lrberge** [comment]
Hi, that's normal: it's because this argument only applies to Tex output. But you're right, that was not mentioned in the help pages, so I've just corrected it.

The technical reason for this is that I want `etable` to return a plain `data.frame` and not to print anything such that its outcome can be used by other functions. Since the `notes` line does not fit into a `data.frame`, then it can't be returned. 

But I could also add extra attributes to the output and define a specific print method which will be able to display the extra attributes, like the `notes`. 
This solution however would only be partial since postprocessing functions would make no use of this extra attribute and the notes would be lost when using them. So it wouldn't be a full win. 

As you can see there are some technical difficulties that need to be resolved and there are no problem-free solution yet. So currently `notes` is not working for non-Tex output, although it may change in the future.

In any case, here's an easy fix you can use:
```R
library(fixest)
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
est = feols(y ~ x1, base)

# Own postprocessing function
my_pp = function(x, my_notes){
    print(x)
    cat("Notes: ", paste0(my_notes, collapse = "\n"), "\n", sep = "")
}

# Defining the postprocessing function to use by default
setFixest_etable(postprocess.df = my_pp)

# Now you can use the new argument my_notes
etable(est, my_notes = "This is a short note.")
#>                               est
#> Dependent Var.:                 y
#>                                  
#> (Intercept)     6.526*** (0.4789)
#> x1               -0.2234 (0.1551)
#> _______________ _________________
#> S.E. type                Standard
#> Observations                  150
#> R2                        0.01382
#> Adj. R2                   0.00716
#> Notes: This is a short note. 
```

**Comment by Annyan233** [comment]
Thanks so much for your sharing!
