### ISSUE TITLE
List of suggestions and a possible bug

### ISSUE THREAD

**Issue by reifjulian** [lrberge/fixest#88]
`fixest` is an excellent package, nice work! Special thanks to @grantmcdermott for pointing me to this package and answering some of my initial questions. I tried it out for a research project, and in doing so came up with a few suggestions and encountered one possible bug. 

1. `feols()` allows the user to specify a cluster variable for standard errors. However, when subsequently calling `summary()`, it does not by default use that cluster variable. I recommend changing that default.

2.  It appears that, in order to include an interaction between a continuous variable, `cvar`, and a factor variable, `fvar`, the user needs to use the syntax `i(cvar, fvar)`. It would be helpful to note this in the documentation.

3. Perhaps I missed it, but the documentation does not appear to mention which first-stage F-statistic is being reported. Is it the Cragg-Donald statistic? It would be useful to also report the Kleibergen-Paap rk statistic, which is heteroskedastic-robust. Check out Stata's `ivreg2` documentation for additional details and examples.

4. Possible bug: specifying the `lean=TRUE` option generated an error. Below is an example.
```R
library(fixest)
library(haven)
my_data <- read_dta("https://reifjulian.github.io/MWE_fixest/test_sample.dta")

iv_feols = 
   feols(death_rate_1day ~ 1 |
            ## FEs
            county_fips^month^year + weather2 + 
            monitor_group100[L1sine_angle] + monitor_group100[L1sine_angle2] + 
            monitor_group100[L2sine_angle] + monitor_group100[L2sine_angle2] |
            ## IV
            SO2_conc ~ i(sine_angle, monitor_group100) + i(sine_angle2, monitor_group100), 
         cluster = ~county_fips,
         weights = ~pop,
	 lean=TRUE,
         data = my_data
)
```

**Comment by lyifa** [comment]
I agree with point 1.

**Comment by grantmcdermott** [comment]
FWIW, I’m also in favour of 1 if it can be supported.

For 2, one related and slightly tricky thing &mdash; which has come up when I’ve been helping people migrate to fixest &mdash; is that the `cvar` -> `fvar` order for `i(cvar, fvar)` is reversed for varying slopes, i.e. `fvar[cvar]`. I’d be very hesitant to suggest switching the order of the former because of breaking changes. But it might be emphasizing in the docs that the order has been reversed (and maybe deliberately so?)

**Comment by lrberge** [comment]
Hi, thanks for the suggestions:

  1. I agree this is a counter intuitive behavior (see [#70](https://github.com/lrberge/fixest/issues/70#issuecomment-748202194)). It has been corrected in version 0.8.1 (just out). Please note that I've just corrected some other bugs introduced in this new implementation (sigh, the fumbling around first implementations...).
  2. This function `i` is one of my biggest regrets. The state of that function is the outcome of path dependency. 
Initially it dealt only with pure interactions so it was kind of OK. Then, much later, I augmented its behavior to act like `as.factor()` and I didn't change the order of the arguments not to break code. This led to very counter-intuitive stuff: 
`i(x)` => `x` treated as a factor
`i(x, y)` => `x` as a continuous variable, `y` treated as a factor
Had I seen the full picture around that function I would have never done that. That's why I try to think through many things before implementing new stuff (and hence I'm slow), but here I guess I wasn't slow enough!
Now reversing the order of the arguments is tricky because it implies one of the worst backward incompatibility: the code will produce different results without any error! And I can't even catch for sure wrong usages since if the user used `i(continuous, continuous)` it's just impossible to know.
The design `i(fvar, cvar)` is strictly superior to `i(cvar, fvar)`, so maybe I should make the change since the package is still barely one year old and before it gets more users. 
Any suggestion would be really appreciated!
  3. Yep it's Cragg-Donald, I've now mentioned it in the docs. Thanks for the suggestion but I don't have the time right now to add new stats, maybe later! Btw feel free to make a PR ;-)
  4. In general, assume that any unclear error message is a bug. And a bug it was! I've just corrected it.
Btw just a comment: you can pool variables in `fe[var1, var2]` so that you need not repeat the fe name (in your case `monitor_group100[L1sine_angle, L1sine_angle2, etc]` would work).

**Comment by reifjulian** [comment]
I personally think your package is new enough that it's ok to change to `i(fvar, cvar)`, provided you believe that this fix will be the long-run permanent solution. Breaking backwards compatibility is obviously never appealing, although if R users listen to @grantmcdermott and practice good version control then the negative consequences should be minimal. That said, I am not an experienced user of R (I work primarily in Stata), so I defer to the judgment of others. 

From my perspective, the most important thing is to make everything clear in the documentation. You have a nice [introductory guide](https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html). Would be good to have a section that explicitly shows how to perform every kind of interaction, including in particular this issue of interacting a factor variable with a continuous variable.

**Comment by lyifa** [comment]
I think at this early stage, backward compatibility should not be an issue.

**Comment by grantmcdermott** [comment]
Some quick thoughts:

> The design i(fvar, cvar) is strictly superior to i(cvar, fvar), so maybe I should make the change since the package is still barely one year old and before it gets more users.

Personally, I'd also be in favour with that. As Julian alluded to, it's easy to preserve behaviour for existing projects with **renv** or similar versioning tool. And, while you can't catch all the use cases (e.g. `i(cvar, cvar)`), perhaps something like once-per-session warning is a suitable compromise?

But there are obviously different user groups to consider. One option would be to run a poll to get a wider sense of people's preferences. I'd be happy to set this up and help amplify, probably linking everything through a separate GH issue. (i.e. I'd write up concise version of the the pros and cons of implementing the change, with a link to the poll.) I'd only be able to get to this after I finish teaching today, but let me know!

PS. I've also been thinking about how to consolidate all of **fixest**'s excellent interaction options in the introductory vignette (again, based on my experiences helping new users). I have some ideas but will save that for a separate PR later ;-)

**Comment by lrberge** [comment]
@reifjulian, on the documentation of `i`: yes I agree so far it's not clear enough in the help pages (and the ubiquity of the first argument doesn't help). I'll clarify the doc.

@grantmcdermott: If we go on to change the arguments order, the introduction of a startup message can be a solution. I must confess that I really hate package startup messages, but I guess I can make an exception and introduce one for some time. :-)
 
On the separate issue asking for feedback: That would be fantastic if you could find the time to do it it! :-) That's very generous, thanks!

**Comment by lrberge** [comment]
@reifjulian: I forgot to mention, but regarding the Kleibergen-Paap statistic, it's actually already implemented. It's the "`ivwald1`" statistic: `fitstat(est, "ivwald1")` is a Wald test on the exogenous regressors using the type of VCOV used in `est`, so if you use a non spherical VCOV it should be the Kleibergen-Paap equivalent of Stata's. You can change the type of VCOV with `fitstat(est, "ivwald1", cluster = ~whatever)`.

**Comment by lrberge** [comment]
Ooo I forgot! Thanks for the reminder! :-D (writing doc is such a chore!)
