### ISSUE TITLE
Syntax order for `i()`

### ISSUE THREAD

**Issue by grantmcdermott** [lrberge/fixest#90]
(Following on from https://github.com/lrberge/fixest/issues/88#issuecomment-760133916; see point 2.)

### Issue

**fixest** provides several (highly optimised) shortcuts for interacting and combining variables. The exact syntax and method depends on where this interaction occurs in the model call. For example, we have:

- **`fvar[cvar]`** for [varying slopes](https://lrberge.github.io/fixest/articles/fixest_walkthrough.html#varying-slopes) in the fixed effects slot, e.g. `feols(Sepal.Length ~ 1 | Species[Sepal.Width], data = iris)`
- **`i(cvar, fvar)`** for "regular" [variable interactions](https://lrberge.github.io/fixest/articles/fixest_walkthrough.html#the-function-i-for-factors-and-interactions-1) in the model RHS, e.g. `feols(Sepal.Length ~ i(Sepal.Width, Species), data = iris)`

I'm deliberately highlighting examples where a factor variable (`fvar`) is being interacted with a continuous variable (`cvar`). The slightly tricky thing here is that the order of these variables actually _changes_ between the two cases. For varying slopes, `fvar` needs to come first and then `cvar`. However, for regular interactions with `i()` that order must be reversed. 

Personally, I've found this to be a point of confusion especially for new **fixest** users.

### Question

Should the syntax of `i()` be adjusted to reflect the same order as the varying slopes case (i.e. factors before continuous variables)?  

*Option 1.* No, keep existing ordering: `i(cvar, var)`
- Pros: No breaking changes.
- Cons: Inconsistent ordering compared to the package's other interaction functions/syntax. (But could make more explicit in the documentation.)

*Option 2.* Yes, switch ordering to: `i(fvar, cvar)`
- Pros: Consistent with related methods.
- Cons: Breaking change. (But could warn users at load time, say nothing of tools like **renv** for snapshotting existing projects.)

### Vote!

Feel free to add thoughts and suggestions below, but FWIW I've also created a simple poll to get a sense of people's preferences. Vote [**here**](https://yh60xclkqsx.typeform.com/to/VwoPTt8m).

**Comment by gbekes** [comment]
I think order should not matter in a syntax like this. Instead one solution could be to have stg Stata have, where different types of variables are "labelled" by a suffix, like c. and i. to communicate variable type. Also it makes it easier to read code. If you have labels, order cannot matter.

**Comment by clukewatson** [comment]
If there is a good enough description (and example) in the help file / vignette, then I would not introduce a break in code.

**Comment by lrberge** [comment]
@gbekes: I'm open to introduce new ways. Could you provide a sketch of your ideal implementation?

**Comment by gbekes** [comment]
I mean (being less than really helpful, I'm afraid) ---my point is the order should not determine how things are done, so it would be nice to keep the old version to enure backward compatibility but add 
i(cvar, var) =  i(f.fvar, c.cvar)=i(c.cvar, f.fvar), ie introduce another way to signal what you want instead of order.

**Comment by lrberge** [comment]
Thanks for clarifying.

**Comment by grantmcdermott** [comment]
I'll probably close the [poll](https://yh60xclkqsx.typeform.com/to/VwoPTt8m) soon, but in the interests of transparency so far we have:

- 3 in favour Option 1 (i.e. status quo)
- 12 in favour of Option 2 (i.e. change the order).

**Comment by lrberge** [comment]
Thanks Grant! Very informative poll, and clear winner (so far!) :-)

**Comment by adamaltmejd** [comment]
What is the reason for deviating from standard syntax here? Why not just be explicit, treat factors as factors and numerical variables as continues and then just use the regular R formula syntax ":" for interactions?

Base can easily be set as the first level of a factor. Or you could provide a helper function to set the base, or even add it as an extra command to factor() if called from within a fixest formula.

Another benefit of course is that one someone wants multiple interactions. Not clear how to do that with i(). Instead of `i(cvar, fvar)` one would write `cvar:factor(fvar)` if fvar is not already a factor.

**Comment by lrberge** [comment]
Using `:` is not handy to deal with interactions since leaving references out is a pain in the neck, that's why I've created the `interact()` function. So that's why using `:` is not a solution. Btw you're always free **not** to use new tools ;-).

Overloading the `factor` function within `fixest` wouldn't be good coding practice since it would bring confusion to the users, and I personally don't like overwriting existing functions. Btw `i` can be used out of `fixest` in other estimating functions, so the previous solution would be less general.

Multiple interaction: simply use `i(c1*c2, fvar)`.

Adding a new function name that differ from the original one before merging is not a good solution. It will bring **a lot** of confusion to the users and will be very difficult to explain properly in the help pages.

To conclude, I really think the argument inversion is the superior solution. For sure it will lead to breaking changes (sometimes unnoticeable, the worst), but be certain I'm not doing it lightly (https://github.com/lrberge/fixest/issues/88#issuecomment-760133916). However it will be the first in the package existence, and since it's for the greater good, so be it!

**Comment by lrberge** [comment]
Thanks a lot Grant for creating this issue! I've made up my mind. When I have the time I'll change that function, and I hope for the better!
